import { Terminal } from "@xterm/xterm";
import { FitAddon } from "@xterm/addon-fit";
import "@xterm/xterm/css/xterm.css";
import "./styles.css";

type MeResponse = { authenticated: boolean; username?: string };

type LayoutSurface = {
  id: string;
  title?: string;
  focused?: boolean;
  snapshot?: string;
  cols?: number;
  rows?: number;
  cursorX?: number;
  cursorY?: number;
  x?: number;
  y?: number;
  w?: number;
  h?: number;
};

type LayoutTab = {
  index: number;
  title?: string;
  focusedSurfaceId?: string;
  surfaces: LayoutSurface[];
};

type RelayMessage = {
  type?: unknown;
  data?: unknown;
  encoding?: unknown;
  message?: unknown;
  surfaceId?: unknown;
  activeTab?: unknown;
  tabs?: unknown;
};

type SurfaceView = {
  panel: HTMLElement;
  title: HTMLSpanElement;
  meta: HTMLElement;
  host: HTMLDivElement;
  term: Terminal;
  fit: FitAddon;
  decoder: TextDecoder;
  disposeInput: { dispose(): void };
  resizeObserver: ResizeObserver | null;
  fitQueued: boolean;
  hasLiveOutput: boolean;
  snapshotApplied: boolean;
  opened: boolean;
  pendingOutput: string;
  remoteCols: number | null;
  remoteRows: number | null;
};

type ControlState = "idle" | "pending" | "granted";
const SESSION_KEY_STORAGE_KEY = "phantty.remote.sessionKey";

const appRoot = document.querySelector<HTMLElement>("#app");

if (!appRoot) {
  throw new Error("Missing app root");
}

const app: HTMLElement = appRoot;
const encoder = new TextEncoder();

let socket: WebSocket | null = null;
let layoutState: { activeTab: number; tabs: LayoutTab[] } | null = null;
let selectedTabIndex = 0;
let selectedSurfaceId: string | null = null;
let surfaceViews = new Map<string, SurfaceView>();
let notices: string[] = [];
let controlState: ControlState = "idle";
let hasSeenLayout = false;

function api(path: string, init?: RequestInit): Promise<Response> {
  return fetch(path, {
    credentials: "same-origin",
    headers: { "content-type": "application/json", ...(init?.headers ?? {}) },
    ...init,
  });
}

async function loadMe(): Promise<MeResponse> {
  const res = await api("/api/me");
  if (!res.ok) return { authenticated: false };
  return res.json() as Promise<MeResponse>;
}

function renderLogin(message = ""): void {
  app.innerHTML = `
    <section class="shell auth-shell">
      <div class="brand">Phantty Remote</div>
      <form class="panel auth-panel" id="login-form">
        <h1>Sign in to your relay</h1>
        <p>Single-user access is required before any local session key can be used.</p>
        <label>
          Username
          <input name="username" autocomplete="username" required />
        </label>
        <label>
          Password
          <input name="password" type="password" autocomplete="current-password" required />
        </label>
        <button type="submit">Sign in</button>
        <output class="form-message">${escapeText(message)}</output>
      </form>
    </section>
  `;

  const form = document.querySelector<HTMLFormElement>("#login-form");
  form?.addEventListener("submit", async (event) => {
    event.preventDefault();
    const data = new FormData(form);
    const res = await api("/api/login", {
      method: "POST",
      body: JSON.stringify({
        username: String(data.get("username") ?? ""),
        password: String(data.get("password") ?? ""),
      }),
    });
    if (!res.ok) {
      renderLogin("Login failed");
      return;
    }
    renderConsole();
  });
}

function renderConsole(): void {
  const savedSessionKey = readSavedSessionKey();
  app.innerHTML = `
    <section class="console-shell">
      <aside class="sidebar">
        <div class="brand">Phantty Remote</div>
        <form id="connect-form" class="panel">
          <h1>Connect session</h1>
          <p>Enter the key generated by this Phantty instance.</p>
          <label>
            Session key
            <input name="session" spellcheck="false" autocomplete="off" value="${escapeText(savedSessionKey)}" required />
          </label>
          <div class="form-actions">
            <button type="submit">Connect</button>
            <button type="button" class="secondary-button" id="clear-session-button">Clear saved</button>
          </div>
        </form>
        <div class="panel status-panel">
          <span class="status-dot" id="status-dot"></span>
          <span id="status-text">Not connected</span>
        </div>
        <div class="panel remote-tabs-panel">
          <div class="panel-label">Tabs</div>
          <div id="remote-tabs" class="remote-tabs empty">Waiting for layout...</div>
        </div>
        <div class="panel notice-panel">
          <div class="panel-label">Relay</div>
          <div id="notice-log" class="notice-log">No relay events yet.</div>
        </div>
        <button class="ghost-button" id="logout-button">Sign out</button>
      </aside>
      <section class="terminal-panel">
        <div class="terminal-toolbar">
          <span id="workspace-title">Remote workspace</span>
          <div class="terminal-actions">
            <span class="control-state" id="control-state">Read-only</span>
            <button type="button" class="control-button" id="request-control-button">Request control</button>
            <span class="toolbar-hint">Read-only until local approval</span>
          </div>
        </div>
        <div id="remote-panels" class="panels-stage empty">
          <div class="empty-state">Connected panels will appear here.</div>
        </div>
      </section>
    </section>
  `;

  document.querySelector<HTMLButtonElement>("#logout-button")?.addEventListener("click", async () => {
    await api("/api/logout", { method: "POST" });
    socket?.close();
    disposeSurfaceViews();
    renderLogin();
  });

  document.querySelector<HTMLFormElement>("#connect-form")?.addEventListener("submit", (event) => {
    event.preventDefault();
    const form = event.currentTarget as HTMLFormElement;
    const data = new FormData(form);
    const sessionKey = String(data.get("session") ?? "").trim();
    saveSessionKey(sessionKey);
    connect(sessionKey);
  });

  const sessionInput = document.querySelector<HTMLInputElement>("#connect-form input[name='session']");
  sessionInput?.addEventListener("input", () => saveSessionKey(sessionInput.value.trim()));
  sessionInput?.addEventListener("change", () => saveSessionKey(sessionInput.value.trim()));

  document.querySelector<HTMLButtonElement>("#clear-session-button")?.addEventListener("click", () => {
    clearSessionKey();
    if (sessionInput) sessionInput.value = "";
    addNotice("Saved session key cleared.");
  });

  document.querySelector<HTMLButtonElement>("#request-control-button")?.addEventListener("click", requestControl);
  updateControlUi();
  if (savedSessionKey) queueMicrotask(() => connect(savedSessionKey));
}

function connect(sessionKey: string): void {
  if (!sessionKey) return;
  socket?.close();
  disposeSurfaceViews();
  layoutState = null;
  selectedSurfaceId = null;
  notices = [];
  controlState = "idle";
  hasSeenLayout = false;
  saveSessionKey(sessionKey);
  renderRemoteWorkspace();
  updateControlUi();

  const protocol = location.protocol === "https:" ? "wss:" : "ws:";
  socket = new WebSocket(`${protocol}//${location.host}/ws/browser?session=${encodeURIComponent(sessionKey)}`);
  setStatus("connecting", "Connecting...");
  updateControlUi();

  socket.addEventListener("open", () => {
    setStatus("online", "Connected");
    addNotice("Connected. Waiting for Phantty layout...");
    updateControlUi();
  });

  socket.addEventListener("close", () => {
    setStatus("offline", "Disconnected");
    applyControlState("idle");
  });

  socket.addEventListener("message", (event) => {
    if (typeof event.data !== "string") return;
    const message = safeJson(event.data);
    if (!message) return;

    if (isLayoutMessage(message)) {
      layoutState = normalizeLayout(message);
      if (!hasSeenLayout) {
        selectedTabIndex = layoutState.activeTab;
        hasSeenLayout = true;
      } else if (!layoutState.tabs.some((tab) => tab.index === selectedTabIndex)) {
        selectedTabIndex = layoutState.activeTab;
      }
      const activeTab = currentTab();
      if (!selectedSurfaceId || !activeTab?.surfaces.some((surface) => surface.id === selectedSurfaceId)) {
        selectedSurfaceId = activeTab?.focusedSurfaceId ?? activeTab?.surfaces[0]?.id ?? selectedSurfaceId;
      }
      reconcileSurfaceViews();
      renderRemoteWorkspace();
      return;
    }

    if (message.type === "output" && typeof message.data === "string") {
      writeLegacyOutput(message.data);
    } else if (
      message.type === "output-bytes" &&
      message.encoding === "hex" &&
      typeof message.data === "string"
    ) {
      const surfaceId = typeof message.surfaceId === "string" ? message.surfaceId : selectedSurfaceId;
      const bytes = decodeHex(message.data);
      if (surfaceId && bytes) writeSurfaceBytes(surfaceId, bytes);
    } else if (message.type === "control-requested") {
      applyControlState("pending", "Waiting for local approval in Phantty...");
    } else if (message.type === "control-granted") {
      applyControlState("granted", "Remote input is enabled");
    } else if (message.type === "control-revoked") {
      applyControlState("idle", "Remote input returned to read-only");
    } else if (message.type === "input-denied" && typeof message.message === "string") {
      addNotice(message.message);
    } else if (message.type === "notice" && typeof message.message === "string") {
      addNotice(message.message);
    }
  });
}

function renderRemoteWorkspace(): void {
  renderRemoteTabs();
  renderRemotePanels();
  renderNotices();
  updateControlUi();
}

function renderRemoteTabs(): void {
  const tabsRoot = document.querySelector<HTMLDivElement>("#remote-tabs");
  if (!tabsRoot) return;

  if (!layoutState || layoutState.tabs.length === 0) {
    tabsRoot.className = "remote-tabs empty";
    tabsRoot.textContent = "Waiting for layout...";
    return;
  }

  tabsRoot.className = "remote-tabs";
  tabsRoot.innerHTML = layoutState.tabs
    .map((tab) => {
      const active = tab.index === selectedTabIndex ? " active" : "";
      const title = escapeText(tab.title || `Tab ${tab.index + 1}`);
      return `<button type="button" class="tab-chip${active}" data-tab-index="${tab.index}">${title}<span>${tab.surfaces.length}</span></button>`;
    })
    .join("");

  tabsRoot.querySelectorAll<HTMLButtonElement>("[data-tab-index]").forEach((button) => {
    button.addEventListener("click", () => {
      selectedTabIndex = Number(button.dataset.tabIndex);
      const activeTab = currentTab();
      selectedSurfaceId = activeTab?.focusedSurfaceId ?? activeTab?.surfaces[0]?.id ?? selectedSurfaceId;
      renderRemoteWorkspace();
    });
  });
}

function renderRemotePanels(): void {
  const panelsRoot = document.querySelector<HTMLDivElement>("#remote-panels");
  const titleRoot = document.querySelector<HTMLSpanElement>("#workspace-title");
  if (!panelsRoot) return;

  const tab = currentTab();
  if (!tab || tab.surfaces.length === 0) {
    panelsRoot.className = "panels-stage empty";
    panelsRoot.replaceChildren(emptyState("No panels for this tab yet."));
    if (titleRoot) titleRoot.textContent = "Remote workspace";
    return;
  }

  if (titleRoot) titleRoot.textContent = tab.title || `Tab ${tab.index + 1}`;
  panelsRoot.className = "panels-stage";
  const visible = new Set(tab.surfaces.map((surface) => surface.id));

  for (const surface of tab.surfaces) {
    const view = ensureSurfaceView(surface.id);
    view.panel.className = `remote-panel${surface.id === selectedSurfaceId ? " selected" : ""}`;
    view.panel.style.left = `${(surface.x ?? 0) * 100}%`;
    view.panel.style.top = `${(surface.y ?? 0) * 100}%`;
    view.panel.style.width = `${Math.max(0.05, surface.w ?? 1) * 100}%`;
    view.panel.style.height = `${Math.max(0.05, surface.h ?? 1) * 100}%`;
    view.panel.dataset.surfaceId = surface.id;
    view.title.textContent = surface.title || shortSurfaceId(surface.id);
    view.meta.textContent = surface.focused ? "focused" : shortSurfaceId(surface.id);
    view.remoteCols = validPositiveInteger(surface.cols);
    view.remoteRows = validPositiveInteger(surface.rows);

    if (view.panel.parentElement !== panelsRoot) {
      panelsRoot.appendChild(view.panel);
    }

    if (!view.opened) {
      view.term.open(view.host);
      view.opened = true;
      view.resizeObserver = new ResizeObserver(() => scheduleFit(view));
      view.resizeObserver.observe(view.host);
      flushPendingOutput(view);
    }
    updateSurfaceCursor(view, surface.id);
    applyInitialSnapshot(view, surface);
    scheduleFit(view);

    if (surface.id === selectedSurfaceId && document.activeElement && view.panel.contains(document.activeElement)) {
      view.term.focus();
    }
  }

  for (const [surfaceId, view] of surfaceViews) {
    if (!visible.has(surfaceId) && view.panel.parentElement === panelsRoot) {
      view.panel.remove();
    }
  }
}

function ensureSurfaceView(surfaceId: string): SurfaceView {
  const existing = surfaceViews.get(surfaceId);
  if (existing) return existing;

  const host = document.createElement("div");
  host.className = "terminal-host";
  const panel = document.createElement("section");
  panel.className = "remote-panel";
  panel.dataset.surfaceId = surfaceId;
  const header = document.createElement("div");
  header.className = "panel-header";
  const title = document.createElement("span");
  const meta = document.createElement("small");
  header.appendChild(title);
  header.appendChild(meta);
  const mount = document.createElement("div");
  mount.className = "terminal-mount";
  mount.appendChild(host);
  panel.appendChild(header);
  panel.appendChild(mount);
  panel.addEventListener("pointerdown", () => {
    selectedSurfaceId = surfaceId;
    renderRemotePanels();
  });
  panel.addEventListener("click", () => {
    selectedSurfaceId = surfaceId;
    renderRemotePanels();
    ensureSurfaceView(surfaceId).term.focus();
  });

  const fit = new FitAddon();
  const term = new Terminal({
    cursorBlink: true,
    cursorInactiveStyle: "outline",
    cursorStyle: "bar",
    cursorWidth: 2,
    convertEol: true,
    disableStdin: controlState !== "granted",
    fontFamily: '"JetBrains Mono", "Cascadia Mono", monospace',
    fontSize: 13,
    scrollback: 0,
    theme: {
      background: "#090f17",
      foreground: "#dce7f3",
      cursor: "#ffd479",
      selectionBackground: "#334155",
    },
  });
  term.loadAddon(fit);

  const view: SurfaceView = {
    panel,
    title,
    meta,
    host,
    term,
    fit,
    decoder: new TextDecoder(),
    disposeInput: term.onData((data) => sendInputBytes(surfaceId, data)),
    resizeObserver: null,
    fitQueued: false,
    hasLiveOutput: false,
    snapshotApplied: false,
    opened: false,
    pendingOutput: "",
    remoteCols: null,
    remoteRows: null,
  };
  surfaceViews.set(surfaceId, view);
  return view;
}

function reconcileSurfaceViews(): void {
  if (!layoutState) return;
  const live = new Set(layoutState.tabs.flatMap((tab) => tab.surfaces.map((surface) => surface.id)));
  for (const [surfaceId, view] of surfaceViews) {
    if (!live.has(surfaceId)) {
      view.resizeObserver?.disconnect();
      view.disposeInput.dispose();
      view.term.dispose();
      surfaceViews.delete(surfaceId);
    }
  }
}

function disposeSurfaceViews(): void {
  for (const view of surfaceViews.values()) {
    view.resizeObserver?.disconnect();
    view.disposeInput.dispose();
    view.term.dispose();
  }
  surfaceViews = new Map();
}

function writeSurfaceBytes(surfaceId: string, bytes: Uint8Array): void {
  const view = ensureSurfaceView(surfaceId);
  view.hasLiveOutput = true;
  writeSurfaceText(view, view.decoder.decode(bytes, { stream: true }));
}

function writeLegacyOutput(data: string): void {
  const surfaceId = selectedSurfaceId ?? currentTab()?.surfaces[0]?.id ?? "legacy";
  const view = ensureSurfaceView(surfaceId);
  view.hasLiveOutput = true;
  writeSurfaceText(view, data);
}

function sendInputBytes(surfaceId: string, data: string): void {
  if (!socket || socket.readyState !== WebSocket.OPEN) return;
  if (controlState !== "granted") return;
  socket.send(
    JSON.stringify({
      type: "input-bytes",
      surfaceId,
      encoding: "hex",
      data: encodeHex(encoder.encode(data)),
    }),
  );
}

function requestControl(): void {
  if (!socket || socket.readyState !== WebSocket.OPEN) {
    addNotice("Connect a Phantty session first.");
    return;
  }
  if (controlState === "granted") return;

  applyControlState("pending");
  socket.send(JSON.stringify({ type: "request-control" }));
  addNotice("Control request sent. Grant it in Phantty with Ctrl+Shift+Y.");
}

function applyControlState(next: ControlState, notice?: string): void {
  const changed = controlState !== next;
  controlState = next;
  updateControlUi();
  if (notice && changed) addNotice(notice);
}

function updateControlUi(): void {
  const connected = socket?.readyState === WebSocket.OPEN;
  const button = document.querySelector<HTMLButtonElement>("#request-control-button");
  const label = document.querySelector<HTMLSpanElement>("#control-state");
  const hint = document.querySelector<HTMLSpanElement>(".toolbar-hint");

  if (button) {
    button.disabled = !connected || controlState === "pending" || controlState === "granted";
    button.textContent =
      controlState === "granted" ? "Control enabled" : controlState === "pending" ? "Waiting local grant" : "Request control";
  }
  if (label) {
    label.dataset.state = controlState;
    label.textContent =
      controlState === "granted" ? "Input enabled" : controlState === "pending" ? "Pending approval" : "Read-only";
  }
  if (hint) {
    hint.textContent = controlState === "granted" ? "Click a panel, then type" : "Read-only until local approval";
  }

  for (const [surfaceId, view] of surfaceViews) {
    view.term.options.disableStdin = controlState !== "granted";
    updateSurfaceCursor(view, surfaceId);
  }
}

function updateSurfaceCursor(view: SurfaceView, surfaceId: string): void {
  const selected = surfaceId === selectedSurfaceId;
  view.term.options.cursorBlink = selected && controlState === "granted";
  view.term.options.cursorInactiveStyle = selected ? "outline" : "none";
}

function scheduleFit(view: SurfaceView): void {
  if (view.fitQueued) return;
  view.fitQueued = true;
  requestAnimationFrame(() => {
    view.fitQueued = false;
    if (!view.host.isConnected) return;
    try {
      if (view.remoteCols && view.remoteRows) {
        if (view.term.cols !== view.remoteCols || view.term.rows !== view.remoteRows) {
          view.term.resize(view.remoteCols, view.remoteRows);
        }
      } else {
        view.fit.fit();
      }
      view.term.refresh(0, Math.max(0, view.term.rows - 1));
    } catch {
      // xterm can briefly report zero-sized panels while layout is settling.
    }
  });
}

function applyInitialSnapshot(view: SurfaceView, surface: LayoutSurface): void {
  if (view.snapshotApplied || view.hasLiveOutput || !surface.snapshot) return;
  view.snapshotApplied = true;
  requestAnimationFrame(() => {
    if (!view.host.isConnected || view.hasLiveOutput) return;
    try {
      if (view.remoteCols && view.remoteRows) {
        view.term.resize(view.remoteCols, view.remoteRows);
      } else {
        view.fit.fit();
      }
    } catch {
      // xterm can briefly report zero-sized panels while layout is settling.
    }
    view.term.reset();
    view.term.write(surface.snapshot + cursorMoveSequence(surface));
    view.term.refresh(0, Math.max(0, view.term.rows - 1));
  });
}

function writeSurfaceText(view: SurfaceView, text: string): void {
  if (!text) return;
  if (!view.opened) {
    view.pendingOutput = capPendingOutput(view.pendingOutput + text);
    return;
  }
  flushPendingOutput(view);
  view.term.write(text);
}

function flushPendingOutput(view: SurfaceView): void {
  if (!view.opened || !view.pendingOutput) return;
  const pending = view.pendingOutput;
  view.pendingOutput = "";
  view.term.write(pending);
}

function capPendingOutput(value: string): string {
  const limit = 128 * 1024;
  return value.length > limit ? value.slice(value.length - limit) : value;
}

function cursorMoveSequence(surface: LayoutSurface): string {
  const x = validNonNegativeInteger(surface.cursorX);
  const y = validNonNegativeInteger(surface.cursorY);
  if (x === null || y === null) return "";
  return `\x1b[${y + 1};${x + 1}H`;
}

function validPositiveInteger(value: unknown): number | null {
  const next = validNonNegativeInteger(value);
  return next !== null && next > 0 ? next : null;
}

function validNonNegativeInteger(value: unknown): number | null {
  if (typeof value !== "number" || !Number.isFinite(value)) return null;
  const next = Math.floor(value);
  return next >= 0 ? next : null;
}

function readSavedSessionKey(): string {
  try {
    return localStorage.getItem(SESSION_KEY_STORAGE_KEY)?.trim() ?? "";
  } catch {
    return "";
  }
}

function saveSessionKey(sessionKey: string): void {
  if (!sessionKey) {
    clearSessionKey();
    return;
  }
  try {
    localStorage.setItem(SESSION_KEY_STORAGE_KEY, sessionKey);
  } catch {
    // Storage may be unavailable in restricted browser contexts.
  }
}

function emptyState(text: string): HTMLDivElement {
  const node = document.createElement("div");
  node.className = "empty-state";
  node.textContent = text;
  return node;
}

function clearSessionKey(): void {
  try {
    localStorage.removeItem(SESSION_KEY_STORAGE_KEY);
  } catch {
    // Storage may be unavailable in restricted browser contexts.
  }
}

function currentTab(): LayoutTab | null {
  if (!layoutState) return null;
  return (
    layoutState.tabs.find((tab) => tab.index === selectedTabIndex) ??
    layoutState.tabs.find((tab) => tab.index === layoutState?.activeTab) ??
    layoutState.tabs[0] ??
    null
  );
}

function isLayoutMessage(message: RelayMessage): boolean {
  return message.type === "layout" && Array.isArray(message.tabs);
}

function normalizeLayout(message: RelayMessage): { activeTab: number; tabs: LayoutTab[] } {
  const activeTab = typeof message.activeTab === "number" ? message.activeTab : 0;
  const rawTabs = Array.isArray(message.tabs) ? message.tabs : [];
  const tabs: LayoutTab[] = rawTabs
    .map((raw): LayoutTab | null => {
      if (!raw || typeof raw !== "object") return null;
      const tab = raw as Record<string, unknown>;
      const index = typeof tab.index === "number" ? tab.index : 0;
      const surfaces = Array.isArray(tab.surfaces)
        ? tab.surfaces.map(normalizeSurface).filter((surface): surface is LayoutSurface => Boolean(surface))
        : [];
      return {
        index,
        title: typeof tab.title === "string" ? tab.title : `Tab ${index + 1}`,
        focusedSurfaceId: typeof tab.focusedSurfaceId === "string" ? tab.focusedSurfaceId : surfaces[0]?.id,
        surfaces,
      };
    })
    .filter((tab): tab is LayoutTab => Boolean(tab));
  return { activeTab, tabs };
}

function normalizeSurface(raw: unknown): LayoutSurface | null {
  if (!raw || typeof raw !== "object") return null;
  const surface = raw as Record<string, unknown>;
  if (typeof surface.id !== "string") return null;
  return {
    id: surface.id,
    title: typeof surface.title === "string" ? surface.title : shortSurfaceId(surface.id),
    focused: surface.focused === true,
    snapshot: typeof surface.snapshot === "string" ? surface.snapshot : "",
    cols: numberOr(surface.cols, 0),
    rows: numberOr(surface.rows, 0),
    cursorX: numberOr(surface.cursorX, 0),
    cursorY: numberOr(surface.cursorY, 0),
    x: numberOr(surface.x, 0),
    y: numberOr(surface.y, 0),
    w: numberOr(surface.w, 1),
    h: numberOr(surface.h, 1),
  };
}

function numberOr(value: unknown, fallback: number): number {
  return typeof value === "number" && Number.isFinite(value) ? value : fallback;
}

function setStatus(kind: "offline" | "connecting" | "online", text: string): void {
  const dot = document.querySelector<HTMLSpanElement>("#status-dot");
  const label = document.querySelector<HTMLSpanElement>("#status-text");
  if (dot) dot.dataset.state = kind;
  if (label) label.textContent = text;
}

function addNotice(message: string): void {
  notices = [...notices.slice(-5), message];
  renderNotices();
}

function renderNotices(): void {
  const root = document.querySelector<HTMLDivElement>("#notice-log");
  if (!root) return;
  if (notices.length === 0) {
    root.textContent = "No relay events yet.";
    return;
  }
  root.innerHTML = notices.map((notice) => `<div>${escapeText(notice)}</div>`).join("");
}

function safeJson(data: string): RelayMessage | null {
  try {
    return JSON.parse(data) as RelayMessage;
  } catch {
    return null;
  }
}

function decodeHex(hex: string): Uint8Array | null {
  if (hex.length % 2 !== 0) return null;
  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < bytes.length; i += 1) {
    const value = Number.parseInt(hex.slice(i * 2, i * 2 + 2), 16);
    if (Number.isNaN(value)) return null;
    bytes[i] = value;
  }
  return bytes;
}

function encodeHex(bytes: Uint8Array): string {
  return Array.from(bytes, (byte) => byte.toString(16).padStart(2, "0")).join("");
}

function shortSurfaceId(id: string): string {
  return id.length > 6 ? id.slice(-6) : id;
}

function escapeText(value: string): string {
  return value.replace(/[&<>"']/g, (ch) => {
    switch (ch) {
      case "&":
        return "&amp;";
      case "<":
        return "&lt;";
      case ">":
        return "&gt;";
      case '"':
        return "&quot;";
      default:
        return "&#39;";
    }
  });
}

void loadMe().then((me) => {
  if (me.authenticated) renderConsole();
  else renderLogin();
});
