import { Terminal } from "@xterm/xterm";
import "@xterm/xterm/css/xterm.css";
import "./styles.css";

type MeResponse = { authenticated: boolean; username?: string };

const appRoot = document.querySelector<HTMLElement>("#app");

if (!appRoot) {
  throw new Error("Missing app root");
}

const app: HTMLElement = appRoot;

let socket: WebSocket | null = null;
let term: Terminal | null = null;
let outputDecoder = new TextDecoder();

function api(path: string, init?: RequestInit): Promise<Response> {
  return fetch(path, {
    credentials: "same-origin",
    headers: { "content-type": "application/json", ...(init?.headers ?? {}) },
    ...init,
  });
}

async function loadMe(): Promise<MeResponse> {
  const res = await api("/api/me");
  if (!res.ok) return { authenticated: false };
  return res.json() as Promise<MeResponse>;
}

function renderLogin(message = ""): void {
  app.innerHTML = `
    <section class="shell auth-shell">
      <div class="brand">Phantty Remote</div>
      <form class="panel auth-panel" id="login-form">
        <h1>Sign in to your relay</h1>
        <p>Single-user access is required before any local session key can be used.</p>
        <label>
          Username
          <input name="username" autocomplete="username" required />
        </label>
        <label>
          Password
          <input name="password" type="password" autocomplete="current-password" required />
        </label>
        <button type="submit">Sign in</button>
        <output class="form-message">${escapeText(message)}</output>
      </form>
    </section>
  `;

  const form = document.querySelector<HTMLFormElement>("#login-form");
  form?.addEventListener("submit", async (event) => {
    event.preventDefault();
    const data = new FormData(form);
    const res = await api("/api/login", {
      method: "POST",
      body: JSON.stringify({
        username: String(data.get("username") ?? ""),
        password: String(data.get("password") ?? ""),
      }),
    });
    if (!res.ok) {
      renderLogin("Login failed");
      return;
    }
    renderConsole();
  });
}

function renderConsole(): void {
  app.innerHTML = `
    <section class="console-shell">
      <aside class="sidebar">
        <div class="brand">Phantty Remote</div>
        <form id="connect-form" class="panel">
          <h1>Connect session</h1>
          <p>Enter the one-time key generated by Phantty after local sharing is enabled.</p>
          <label>
            Session key
            <input name="session" spellcheck="false" autocomplete="off" required />
          </label>
          <button type="submit">Connect read-only</button>
        </form>
        <div class="panel status-panel">
          <span class="status-dot" id="status-dot"></span>
          <span id="status-text">Not connected</span>
        </div>
        <button class="ghost-button" id="logout-button">Sign out</button>
      </aside>
      <section class="terminal-panel">
        <div class="terminal-toolbar">
          <span>Read-only terminal relay</span>
          <button id="request-control" disabled>Request control</button>
        </div>
        <div id="terminal"></div>
      </section>
    </section>
  `;

  term = new Terminal({
    cursorBlink: false,
    convertEol: true,
    disableStdin: true,
    fontFamily: '"JetBrains Mono", "Cascadia Mono", monospace',
    fontSize: 14,
    theme: {
      background: "#10151d",
      foreground: "#dce7f3",
      cursor: "#ffd479",
      selectionBackground: "#334155",
    },
  });
  term.open(document.querySelector<HTMLDivElement>("#terminal")!);
  term.write("Waiting for a Phantty session...\r\n");

  document.querySelector<HTMLButtonElement>("#logout-button")?.addEventListener("click", async () => {
    await api("/api/logout", { method: "POST" });
    socket?.close();
    renderLogin();
  });

  document.querySelector<HTMLFormElement>("#connect-form")?.addEventListener("submit", (event) => {
    event.preventDefault();
    const form = event.currentTarget as HTMLFormElement;
    const data = new FormData(form);
    connect(String(data.get("session") ?? "").trim());
  });
}

function connect(sessionKey: string): void {
  if (!sessionKey) return;
  socket?.close();

  const protocol = location.protocol === "https:" ? "wss:" : "ws:";
  socket = new WebSocket(`${protocol}//${location.host}/ws/browser?session=${encodeURIComponent(sessionKey)}`);
  setStatus("connecting", "Connecting...");

  socket.addEventListener("open", () => {
    setStatus("online", "Connected read-only");
    outputDecoder = new TextDecoder();
    term?.reset();
    term?.write("Connected. Waiting for Phantty output...\r\n");
  });

  socket.addEventListener("close", () => {
    setStatus("offline", "Disconnected");
  });

  socket.addEventListener("message", (event) => {
    if (typeof event.data !== "string") return;
    const message = safeJson(event.data);
    if (!message) return;
    if (message.type === "output" && typeof message.data === "string") {
      term?.write(message.data);
    } else if (
      message.type === "output-bytes" &&
      message.encoding === "hex" &&
      typeof message.data === "string"
    ) {
      const bytes = decodeHex(message.data);
      if (bytes) term?.write(outputDecoder.decode(bytes, { stream: true }));
    } else if (message.type === "notice" && typeof message.message === "string") {
      term?.write(`\r\n[relay] ${message.message}\r\n`);
    }
  });
}

function setStatus(kind: "offline" | "connecting" | "online", text: string): void {
  const dot = document.querySelector<HTMLSpanElement>("#status-dot");
  const label = document.querySelector<HTMLSpanElement>("#status-text");
  if (dot) dot.dataset.state = kind;
  if (label) label.textContent = text;
}

function safeJson(data: string): { type?: unknown; data?: unknown; encoding?: unknown; message?: unknown } | null {
  try {
    return JSON.parse(data) as { type?: unknown; data?: unknown; encoding?: unknown; message?: unknown };
  } catch {
    return null;
  }
}

function decodeHex(hex: string): Uint8Array | null {
  if (hex.length % 2 !== 0) return null;
  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < bytes.length; i += 1) {
    const value = Number.parseInt(hex.slice(i * 2, i * 2 + 2), 16);
    if (Number.isNaN(value)) return null;
    bytes[i] = value;
  }
  return bytes;
}

function escapeText(value: string): string {
  return value.replace(/[&<>"']/g, (ch) => {
    switch (ch) {
      case "&":
        return "&amp;";
      case "<":
        return "&lt;";
      case ">":
        return "&gt;";
      case '"':
        return "&quot;";
      default:
        return "&#39;";
    }
  });
}

void loadMe().then((me) => {
  if (me.authenticated) renderConsole();
  else renderLogin();
});
