import { Terminal } from "@xterm/xterm";
import "@xterm/xterm/css/xterm.css";
import "./styles.css";

type MeResponse = { authenticated: boolean; username?: string };

type LayoutSurface = {
  id: string;
  title?: string;
  focused?: boolean;
  x?: number;
  y?: number;
  w?: number;
  h?: number;
};

type LayoutTab = {
  index: number;
  title?: string;
  focusedSurfaceId?: string;
  surfaces: LayoutSurface[];
};

type RelayMessage = {
  type?: unknown;
  data?: unknown;
  encoding?: unknown;
  message?: unknown;
  surfaceId?: unknown;
  activeTab?: unknown;
  tabs?: unknown;
};

type SurfaceView = {
  host: HTMLDivElement;
  term: Terminal;
  decoder: TextDecoder;
  disposeInput: { dispose(): void };
};

const appRoot = document.querySelector<HTMLElement>("#app");

if (!appRoot) {
  throw new Error("Missing app root");
}

const app: HTMLElement = appRoot;
const encoder = new TextEncoder();

let socket: WebSocket | null = null;
let layoutState: { activeTab: number; tabs: LayoutTab[] } | null = null;
let selectedTabIndex = 0;
let selectedSurfaceId: string | null = null;
let surfaceViews = new Map<string, SurfaceView>();
let notices: string[] = [];

function api(path: string, init?: RequestInit): Promise<Response> {
  return fetch(path, {
    credentials: "same-origin",
    headers: { "content-type": "application/json", ...(init?.headers ?? {}) },
    ...init,
  });
}

async function loadMe(): Promise<MeResponse> {
  const res = await api("/api/me");
  if (!res.ok) return { authenticated: false };
  return res.json() as Promise<MeResponse>;
}

function renderLogin(message = ""): void {
  app.innerHTML = `
    <section class="shell auth-shell">
      <div class="brand">Phantty Remote</div>
      <form class="panel auth-panel" id="login-form">
        <h1>Sign in to your relay</h1>
        <p>Single-user access is required before any local session key can be used.</p>
        <label>
          Username
          <input name="username" autocomplete="username" required />
        </label>
        <label>
          Password
          <input name="password" type="password" autocomplete="current-password" required />
        </label>
        <button type="submit">Sign in</button>
        <output class="form-message">${escapeText(message)}</output>
      </form>
    </section>
  `;

  const form = document.querySelector<HTMLFormElement>("#login-form");
  form?.addEventListener("submit", async (event) => {
    event.preventDefault();
    const data = new FormData(form);
    const res = await api("/api/login", {
      method: "POST",
      body: JSON.stringify({
        username: String(data.get("username") ?? ""),
        password: String(data.get("password") ?? ""),
      }),
    });
    if (!res.ok) {
      renderLogin("Login failed");
      return;
    }
    renderConsole();
  });
}

function renderConsole(): void {
  app.innerHTML = `
    <section class="console-shell">
      <aside class="sidebar">
        <div class="brand">Phantty Remote</div>
        <form id="connect-form" class="panel">
          <h1>Connect session</h1>
          <p>Enter the key generated by this Phantty instance.</p>
          <label>
            Session key
            <input name="session" spellcheck="false" autocomplete="off" required />
          </label>
          <button type="submit">Connect</button>
        </form>
        <div class="panel status-panel">
          <span class="status-dot" id="status-dot"></span>
          <span id="status-text">Not connected</span>
        </div>
        <div class="panel remote-tabs-panel">
          <div class="panel-label">Tabs</div>
          <div id="remote-tabs" class="remote-tabs empty">Waiting for layout...</div>
        </div>
        <div class="panel notice-panel">
          <div class="panel-label">Relay</div>
          <div id="notice-log" class="notice-log">No relay events yet.</div>
        </div>
        <button class="ghost-button" id="logout-button">Sign out</button>
      </aside>
      <section class="terminal-panel">
        <div class="terminal-toolbar">
          <span id="workspace-title">Remote workspace</span>
          <span class="toolbar-hint">Click a panel, then type</span>
        </div>
        <div id="remote-panels" class="panels-stage empty">
          <div class="empty-state">Connected panels will appear here.</div>
        </div>
      </section>
    </section>
  `;

  document.querySelector<HTMLButtonElement>("#logout-button")?.addEventListener("click", async () => {
    await api("/api/logout", { method: "POST" });
    socket?.close();
    disposeSurfaceViews();
    renderLogin();
  });

  document.querySelector<HTMLFormElement>("#connect-form")?.addEventListener("submit", (event) => {
    event.preventDefault();
    const form = event.currentTarget as HTMLFormElement;
    const data = new FormData(form);
    connect(String(data.get("session") ?? "").trim());
  });
}

function connect(sessionKey: string): void {
  if (!sessionKey) return;
  socket?.close();
  disposeSurfaceViews();
  layoutState = null;
  selectedSurfaceId = null;
  notices = [];
  renderRemoteWorkspace();

  const protocol = location.protocol === "https:" ? "wss:" : "ws:";
  socket = new WebSocket(`${protocol}//${location.host}/ws/browser?session=${encodeURIComponent(sessionKey)}`);
  setStatus("connecting", "Connecting...");

  socket.addEventListener("open", () => {
    setStatus("online", "Connected");
    addNotice("Connected. Waiting for Phantty layout...");
  });

  socket.addEventListener("close", () => {
    setStatus("offline", "Disconnected");
  });

  socket.addEventListener("message", (event) => {
    if (typeof event.data !== "string") return;
    const message = safeJson(event.data);
    if (!message) return;

    if (isLayoutMessage(message)) {
      layoutState = normalizeLayout(message);
      if (!layoutState.tabs.some((tab) => tab.index === selectedTabIndex)) {
        selectedTabIndex = layoutState.activeTab;
      }
      const activeTab = currentTab();
      selectedSurfaceId = activeTab?.focusedSurfaceId ?? activeTab?.surfaces[0]?.id ?? selectedSurfaceId;
      reconcileSurfaceViews();
      renderRemoteWorkspace();
      return;
    }

    if (message.type === "output" && typeof message.data === "string") {
      writeLegacyOutput(message.data);
    } else if (
      message.type === "output-bytes" &&
      message.encoding === "hex" &&
      typeof message.data === "string"
    ) {
      const surfaceId = typeof message.surfaceId === "string" ? message.surfaceId : selectedSurfaceId;
      const bytes = decodeHex(message.data);
      if (surfaceId && bytes) writeSurfaceBytes(surfaceId, bytes);
    } else if (message.type === "notice" && typeof message.message === "string") {
      addNotice(message.message);
    }
  });
}

function renderRemoteWorkspace(): void {
  renderRemoteTabs();
  renderRemotePanels();
  renderNotices();
}

function renderRemoteTabs(): void {
  const tabsRoot = document.querySelector<HTMLDivElement>("#remote-tabs");
  if (!tabsRoot) return;

  if (!layoutState || layoutState.tabs.length === 0) {
    tabsRoot.className = "remote-tabs empty";
    tabsRoot.textContent = "Waiting for layout...";
    return;
  }

  tabsRoot.className = "remote-tabs";
  tabsRoot.innerHTML = layoutState.tabs
    .map((tab) => {
      const active = tab.index === selectedTabIndex ? " active" : "";
      const title = escapeText(tab.title || `Tab ${tab.index + 1}`);
      return `<button type="button" class="tab-chip${active}" data-tab-index="${tab.index}">${title}<span>${tab.surfaces.length}</span></button>`;
    })
    .join("");

  tabsRoot.querySelectorAll<HTMLButtonElement>("[data-tab-index]").forEach((button) => {
    button.addEventListener("click", () => {
      selectedTabIndex = Number(button.dataset.tabIndex);
      const activeTab = currentTab();
      selectedSurfaceId = activeTab?.focusedSurfaceId ?? activeTab?.surfaces[0]?.id ?? selectedSurfaceId;
      renderRemoteWorkspace();
    });
  });
}

function renderRemotePanels(): void {
  const panelsRoot = document.querySelector<HTMLDivElement>("#remote-panels");
  const titleRoot = document.querySelector<HTMLSpanElement>("#workspace-title");
  if (!panelsRoot) return;

  const tab = currentTab();
  if (!tab || tab.surfaces.length === 0) {
    panelsRoot.className = "panels-stage empty";
    panelsRoot.innerHTML = `<div class="empty-state">No panels for this tab yet.</div>`;
    if (titleRoot) titleRoot.textContent = "Remote workspace";
    return;
  }

  if (titleRoot) titleRoot.textContent = tab.title || `Tab ${tab.index + 1}`;
  panelsRoot.className = "panels-stage";
  panelsRoot.innerHTML = "";

  for (const surface of tab.surfaces) {
    const view = ensureSurfaceView(surface.id);
    const panel = document.createElement("section");
    panel.className = `remote-panel${surface.id === selectedSurfaceId ? " selected" : ""}`;
    panel.style.left = `${(surface.x ?? 0) * 100}%`;
    panel.style.top = `${(surface.y ?? 0) * 100}%`;
    panel.style.width = `${Math.max(0.05, surface.w ?? 1) * 100}%`;
    panel.style.height = `${Math.max(0.05, surface.h ?? 1) * 100}%`;
    panel.dataset.surfaceId = surface.id;

    const header = document.createElement("div");
    header.className = "panel-header";
    header.innerHTML = `
      <span>${escapeText(surface.title || shortSurfaceId(surface.id))}</span>
      <small>${surface.focused ? "focused" : shortSurfaceId(surface.id)}</small>
    `;

    const mount = document.createElement("div");
    mount.className = "terminal-mount";
    mount.appendChild(view.host);

    panel.appendChild(header);
    panel.appendChild(mount);
    panelsRoot.appendChild(panel);

    if (!view.host.dataset.opened) {
      view.term.open(view.host);
      view.host.dataset.opened = "true";
      view.term.write(`Panel ${shortSurfaceId(surface.id)} ready\r\n`);
    } else {
      view.term.refresh(0, view.term.rows - 1);
    }

    panel.addEventListener("click", () => {
      selectedSurfaceId = surface.id;
      renderRemotePanels();
      ensureSurfaceView(surface.id).term.focus();
    });
  }
}

function ensureSurfaceView(surfaceId: string): SurfaceView {
  const existing = surfaceViews.get(surfaceId);
  if (existing) return existing;

  const host = document.createElement("div");
  host.className = "terminal-host";
  const term = new Terminal({
    cursorBlink: true,
    convertEol: true,
    disableStdin: false,
    fontFamily: '"JetBrains Mono", "Cascadia Mono", monospace',
    fontSize: 13,
    scrollback: 0,
    theme: {
      background: "#090f17",
      foreground: "#dce7f3",
      cursor: "#ffd479",
      selectionBackground: "#334155",
    },
  });

  const view: SurfaceView = {
    host,
    term,
    decoder: new TextDecoder(),
    disposeInput: term.onData((data) => sendInputBytes(surfaceId, data)),
  };
  surfaceViews.set(surfaceId, view);
  return view;
}

function reconcileSurfaceViews(): void {
  if (!layoutState) return;
  const live = new Set(layoutState.tabs.flatMap((tab) => tab.surfaces.map((surface) => surface.id)));
  for (const [surfaceId, view] of surfaceViews) {
    if (!live.has(surfaceId)) {
      view.disposeInput.dispose();
      view.term.dispose();
      surfaceViews.delete(surfaceId);
    }
  }
}

function disposeSurfaceViews(): void {
  for (const view of surfaceViews.values()) {
    view.disposeInput.dispose();
    view.term.dispose();
  }
  surfaceViews = new Map();
}

function writeSurfaceBytes(surfaceId: string, bytes: Uint8Array): void {
  const view = ensureSurfaceView(surfaceId);
  view.term.write(view.decoder.decode(bytes, { stream: true }));
}

function writeLegacyOutput(data: string): void {
  const surfaceId = selectedSurfaceId ?? currentTab()?.surfaces[0]?.id ?? "legacy";
  ensureSurfaceView(surfaceId).term.write(data);
}

function sendInputBytes(surfaceId: string, data: string): void {
  if (!socket || socket.readyState !== WebSocket.OPEN) return;
  socket.send(
    JSON.stringify({
      type: "input-bytes",
      surfaceId,
      encoding: "hex",
      data: encodeHex(encoder.encode(data)),
    }),
  );
}

function currentTab(): LayoutTab | null {
  if (!layoutState) return null;
  return (
    layoutState.tabs.find((tab) => tab.index === selectedTabIndex) ??
    layoutState.tabs.find((tab) => tab.index === layoutState?.activeTab) ??
    layoutState.tabs[0] ??
    null
  );
}

function isLayoutMessage(message: RelayMessage): boolean {
  return message.type === "layout" && Array.isArray(message.tabs);
}

function normalizeLayout(message: RelayMessage): { activeTab: number; tabs: LayoutTab[] } {
  const activeTab = typeof message.activeTab === "number" ? message.activeTab : 0;
  const rawTabs = Array.isArray(message.tabs) ? message.tabs : [];
  const tabs: LayoutTab[] = rawTabs
    .map((raw): LayoutTab | null => {
      if (!raw || typeof raw !== "object") return null;
      const tab = raw as Record<string, unknown>;
      const index = typeof tab.index === "number" ? tab.index : 0;
      const surfaces = Array.isArray(tab.surfaces)
        ? tab.surfaces.map(normalizeSurface).filter((surface): surface is LayoutSurface => Boolean(surface))
        : [];
      return {
        index,
        title: typeof tab.title === "string" ? tab.title : `Tab ${index + 1}`,
        focusedSurfaceId: typeof tab.focusedSurfaceId === "string" ? tab.focusedSurfaceId : surfaces[0]?.id,
        surfaces,
      };
    })
    .filter((tab): tab is LayoutTab => Boolean(tab));
  return { activeTab, tabs };
}

function normalizeSurface(raw: unknown): LayoutSurface | null {
  if (!raw || typeof raw !== "object") return null;
  const surface = raw as Record<string, unknown>;
  if (typeof surface.id !== "string") return null;
  return {
    id: surface.id,
    title: typeof surface.title === "string" ? surface.title : shortSurfaceId(surface.id),
    focused: surface.focused === true,
    x: numberOr(surface.x, 0),
    y: numberOr(surface.y, 0),
    w: numberOr(surface.w, 1),
    h: numberOr(surface.h, 1),
  };
}

function numberOr(value: unknown, fallback: number): number {
  return typeof value === "number" && Number.isFinite(value) ? value : fallback;
}

function setStatus(kind: "offline" | "connecting" | "online", text: string): void {
  const dot = document.querySelector<HTMLSpanElement>("#status-dot");
  const label = document.querySelector<HTMLSpanElement>("#status-text");
  if (dot) dot.dataset.state = kind;
  if (label) label.textContent = text;
}

function addNotice(message: string): void {
  notices = [...notices.slice(-5), message];
  renderNotices();
}

function renderNotices(): void {
  const root = document.querySelector<HTMLDivElement>("#notice-log");
  if (!root) return;
  if (notices.length === 0) {
    root.textContent = "No relay events yet.";
    return;
  }
  root.innerHTML = notices.map((notice) => `<div>${escapeText(notice)}</div>`).join("");
}

function safeJson(data: string): RelayMessage | null {
  try {
    return JSON.parse(data) as RelayMessage;
  } catch {
    return null;
  }
}

function decodeHex(hex: string): Uint8Array | null {
  if (hex.length % 2 !== 0) return null;
  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < bytes.length; i += 1) {
    const value = Number.parseInt(hex.slice(i * 2, i * 2 + 2), 16);
    if (Number.isNaN(value)) return null;
    bytes[i] = value;
  }
  return bytes;
}

function encodeHex(bytes: Uint8Array): string {
  return Array.from(bytes, (byte) => byte.toString(16).padStart(2, "0")).join("");
}

function shortSurfaceId(id: string): string {
  return id.length > 6 ? id.slice(-6) : id;
}

function escapeText(value: string): string {
  return value.replace(/[&<>"']/g, (ch) => {
    switch (ch) {
      case "&":
        return "&amp;";
      case "<":
        return "&lt;";
      case ">":
        return "&gt;";
      case '"':
        return "&quot;";
      default:
        return "&#39;";
    }
  });
}

void loadMe().then((me) => {
  if (me.authenticated) renderConsole();
  else renderLogin();
});
