import type { StatusKind } from "../types";
import { iconClose, iconKeyboard, iconMenu, themeToggleMarkup } from "../icons";
import { bindThemeToggleButtons } from "../theme";
import { currentTab, state, pushNotice } from "../state";
import { clearSessionKey, maskSessionKey, readSavedSessionKey, saveKbdVisible, saveSessionKey } from "../storage";
import { escapeText, shortSurfaceId } from "../utils";
import { api, connect, disconnect } from "../transport";
import {
  disposeSurfaceViews,
  focusAndFitSelectedSurface,
  refitAllSurfaces,
  renderRemotePanels,
  updateSurfaceCursors,
} from "../surfaces";
import { bindMobileTextInput, renderMobileTextInputMarkup } from "../mobile_text_input";
import { bindVirtualKeyboard, renderVirtualKeyboardMarkup } from "../vkbd";

let viewportRefitBound = false;

export function renderConsole(app: HTMLElement, onLogout: () => void): void {
  const savedSessionKey = readSavedSessionKey();
  const hasSavedSessionKey = savedSessionKey.length > 0;
  let sessionKeyMasked = hasSavedSessionKey;
  const initialSessionInputValue = hasSavedSessionKey ? maskSessionKey(savedSessionKey) : savedSessionKey;

  app.innerHTML = `
    <section class="console-shell" data-kbd-visible="${state.kbdVisible}" data-drawer-open="${state.drawerOpen}">
      <div class="sidebar-backdrop" id="sidebar-backdrop"></div>
      <aside class="sidebar" id="sidebar">
        <div class="sidebar-head">
          <div class="brand">Phantty Remote</div>
          <div class="sidebar-head-actions">
            ${themeToggleMarkup()}
            <button type="button" class="icon-button" id="drawer-close" aria-label="Close menu">
              ${iconClose()}
            </button>
          </div>
        </div>
        <form id="connect-form" class="panel">
          <h1>Connect session</h1>
          <p>Enter the key generated by this Phantty instance.</p>
          <label>
            Session key
            <input name="session" spellcheck="false" autocomplete="off" value="${escapeText(initialSessionInputValue)}" required />
          </label>
          <div class="form-actions">
            <button type="submit">Connect</button>
            <button type="button" class="secondary-button" id="clear-session-button">Clear saved</button>
          </div>
        </form>
        <div class="panel status-panel">
          <span class="status-dot" id="status-dot"></span>
          <span id="status-text">Not connected</span>
        </div>
        <div class="panel remote-tabs-panel">
          <div class="panel-label">Tabs</div>
          <div id="remote-tabs" class="remote-tabs empty">Waiting for layout...</div>
        </div>
        <div class="panel notice-panel">
          <div class="panel-label">Relay</div>
          <div id="notice-log" class="notice-log">No relay events yet.</div>
        </div>
        <button class="ghost-button" id="logout-button">Sign out</button>
      </aside>
      <section class="workspace">
        <header class="mobile-bar">
          <button type="button" class="icon-button" id="drawer-open" aria-label="Open menu">
            ${iconMenu()}
          </button>
          <span class="mobile-bar-title" id="mobile-workspace-title">Phantty Remote</span>
          <span class="status-pip" id="mobile-status-pip" data-state="offline" title="Disconnected"></span>
          <button type="button" class="icon-button" id="kbd-toggle" aria-label="Toggle keyboard">
            ${iconKeyboard()}
          </button>
        </header>
        <div class="surface-strip" id="surface-strip"></div>
        <section class="terminal-panel">
          <div class="terminal-toolbar">
            <span id="workspace-title">Remote workspace</span>
            <div class="terminal-actions">
              <span class="control-state" id="control-state" data-state="granted">Input enabled</span>
              <span class="toolbar-hint">Click a panel, then type</span>
            </div>
          </div>
          <div id="remote-panels" class="panels-stage empty">
            <div class="empty-state">Connected panels will appear here.</div>
          </div>
        </section>
      </section>
      ${renderVirtualKeyboardMarkup()}
      ${renderMobileTextInputMarkup()}
    </section>
  `;

  document.querySelector<HTMLButtonElement>("#logout-button")?.addEventListener("click", async () => {
    await api("/api/logout", { method: "POST" });
    disconnect();
    disposeSurfaceViews();
    onLogout();
  });

  document.querySelector<HTMLFormElement>("#connect-form")?.addEventListener("submit", (event) => {
    event.preventDefault();
    const form = event.currentTarget as HTMLFormElement;
    const data = new FormData(form);
    const typedValue = String(data.get("session") ?? "").trim();
    const sessionKey = sessionKeyMasked && savedSessionKey ? savedSessionKey : typedValue;
    saveSessionKey(sessionKey);
    setDrawerOpen(false);
    connect(sessionKey);
  });

  const sessionInput = document.querySelector<HTMLInputElement>("#connect-form input[name='session']");
  const revealSessionInput = (): void => {
    if (!sessionKeyMasked || !sessionInput) return;
    sessionKeyMasked = false;
    sessionInput.value = "";
  };
  sessionInput?.addEventListener("focus", revealSessionInput);
  sessionInput?.addEventListener("pointerdown", revealSessionInput);
  sessionInput?.addEventListener("input", () => {
    if (sessionKeyMasked) return;
    saveSessionKey(sessionInput.value.trim());
  });
  sessionInput?.addEventListener("change", () => {
    if (sessionKeyMasked) return;
    saveSessionKey(sessionInput.value.trim());
  });

  document.querySelector<HTMLButtonElement>("#clear-session-button")?.addEventListener("click", () => {
    clearSessionKey();
    sessionKeyMasked = false;
    if (sessionInput) sessionInput.value = "";
    pushNotice("Saved session key cleared.");
    renderNotices();
  });

  bindMobileChrome();
  bindViewportRefit();
  bindVirtualKeyboard(() => setKbdVisible(false));
  bindMobileTextInput();
  bindThemeToggleButtons();
  updateInputUi();
  if (savedSessionKey) queueMicrotask(() => connect(savedSessionKey));
}

export function setStatus(kind: StatusKind, text: string): void {
  const dot = document.querySelector<HTMLSpanElement>("#status-dot");
  const label = document.querySelector<HTMLSpanElement>("#status-text");
  const pip = document.querySelector<HTMLSpanElement>("#mobile-status-pip");
  if (dot) dot.dataset.state = kind;
  if (label) label.textContent = text;
  if (pip) {
    pip.dataset.state = kind;
    pip.title = text;
  }
}

export function renderNotices(): void {
  const root = document.querySelector<HTMLDivElement>("#notice-log");
  if (!root) return;
  if (state.notices.length === 0) {
    root.textContent = "No relay events yet.";
    return;
  }
  root.innerHTML = state.notices.map((notice) => `<div>${escapeText(notice)}</div>`).join("");
}

export function renderRemoteTabs(): void {
  const tabsRoot = document.querySelector<HTMLDivElement>("#remote-tabs");
  if (!tabsRoot) return;

  const layout = state.layoutState;
  if (!layout || layout.tabs.length === 0) {
    tabsRoot.className = "remote-tabs empty";
    tabsRoot.textContent = "Waiting for layout...";
    return;
  }

  tabsRoot.className = "remote-tabs";
  tabsRoot.innerHTML = layout.tabs
    .map((tab) => {
      const active = tab.index === state.selectedTabIndex ? " active" : "";
      const title = escapeText(tab.title || `Tab ${tab.index + 1}`);
      return `<button type="button" class="tab-chip${active}" data-tab-index="${tab.index}">${title}<span>${tab.surfaces.length}</span></button>`;
    })
    .join("");

  tabsRoot.querySelectorAll<HTMLButtonElement>("[data-tab-index]").forEach((button) => {
    button.addEventListener("click", () => {
      state.selectedTabIndex = Number(button.dataset.tabIndex);
      const layoutNow = state.layoutState;
      const activeTab = layoutNow?.tabs.find((tab) => tab.index === state.selectedTabIndex) ?? null;
      state.selectedSurfaceId =
        activeTab?.focusedSurfaceId ?? activeTab?.surfaces[0]?.id ?? state.selectedSurfaceId;
      renderRemoteWorkspace();
    });
  });
}

export function renderRemoteWorkspace(): void {
  renderRemoteTabs();
  renderRemotePanels();
  renderSurfaceStrip();
  renderNotices();
  updateInputUi();
}

function renderSurfaceStrip(): void {
  const strip = document.querySelector<HTMLDivElement>("#surface-strip");
  if (!strip) return;
  const tab = currentTab();
  const surfaces = tab?.surfaces ?? [];
  if (surfaces.length <= 1) {
    strip.replaceChildren();
    return;
  }
  strip.innerHTML = surfaces
    .map((surface) => {
      const active = surface.id === state.selectedSurfaceId ? " active" : "";
      const label = escapeText(surface.title || shortSurfaceId(surface.id));
      return `<button type="button" class="surface-chip${active}" data-surface-id="${escapeText(surface.id)}">${label}</button>`;
    })
    .join("");
  strip.querySelectorAll<HTMLButtonElement>("[data-surface-id]").forEach((button) => {
    button.addEventListener("click", () => {
      state.selectedSurfaceId = button.dataset.surfaceId ?? state.selectedSurfaceId;
      renderRemoteWorkspace();
      focusAndFitSelectedSurface();
    });
  });
}

export function updateInputUi(): void {
  const connected = state.socket?.readyState === WebSocket.OPEN;
  const label = document.querySelector<HTMLSpanElement>("#control-state");
  const hint = document.querySelector<HTMLSpanElement>(".toolbar-hint");

  if (label) {
    label.dataset.state = connected ? "granted" : "idle";
    label.textContent = connected ? "Input enabled" : "Input ready";
  }
  if (hint) {
    hint.textContent = connected ? "Click a panel, then type" : "Connect a session to begin";
  }

  updateSurfaceCursors();
}

function bindMobileChrome(): void {
  document.querySelector<HTMLButtonElement>("#drawer-open")?.addEventListener("click", () => {
    setDrawerOpen(true);
  });
  document.querySelector<HTMLButtonElement>("#drawer-close")?.addEventListener("click", () => {
    setDrawerOpen(false);
  });
  document.querySelector<HTMLDivElement>("#sidebar-backdrop")?.addEventListener("click", () => {
    setDrawerOpen(false);
  });
  document.querySelector<HTMLButtonElement>("#kbd-toggle")?.addEventListener("click", () => {
    setKbdVisible(!state.kbdVisible);
  });
}

function bindViewportRefit(): void {
  if (viewportRefitBound) return;
  viewportRefitBound = true;

  const refit = (): void => {
    refitAllSurfaces();
  };

  window.addEventListener("resize", refit, { passive: true });
  window.visualViewport?.addEventListener("resize", refit);
  window.visualViewport?.addEventListener("scroll", refit);
}

function setDrawerOpen(open: boolean): void {
  state.drawerOpen = open;
  const shell = document.querySelector<HTMLElement>(".console-shell");
  if (shell) shell.dataset.drawerOpen = String(open);
}

function setKbdVisible(visible: boolean): void {
  state.kbdVisible = visible;
  saveKbdVisible(visible);
  const shell = document.querySelector<HTMLElement>(".console-shell");
  if (shell) shell.dataset.kbdVisible = String(visible);
  requestAnimationFrame(() => refitAllSurfaces());
}
