/// Embedded themes shipped with WispTerm.
///
/// All 453 themes from Ghostty (https://github.com/ghostty-org/ghostty), plus
/// One Dark Pro from https://github.com/Binaryify/OneDark-Pro,
/// are embedded at compile time. User themes in the app config themes directory
/// take priority over embedded themes.
const std = @import("std");

const Entry = struct {
    name: []const u8,
    data: []const u8,
};

pub const entries = [_]Entry{
    .{ .name = "0x96f", .data = @embedFile("themes/0x96f") },
    .{ .name = "12-bit Rainbow", .data = @embedFile("themes/12-bit Rainbow") },
    .{ .name = "3024 Day", .data = @embedFile("themes/3024 Day") },
    .{ .name = "3024 Night", .data = @embedFile("themes/3024 Night") },
    .{ .name = "Aardvark Blue", .data = @embedFile("themes/Aardvark Blue") },
    .{ .name = "Abernathy", .data = @embedFile("themes/Abernathy") },
    .{ .name = "Adventure", .data = @embedFile("themes/Adventure") },
    .{ .name = "Adventure Time", .data = @embedFile("themes/Adventure Time") },
    .{ .name = "Adwaita", .data = @embedFile("themes/Adwaita") },
    .{ .name = "Adwaita Dark", .data = @embedFile("themes/Adwaita Dark") },
    .{ .name = "Afterglow", .data = @embedFile("themes/Afterglow") },
    .{ .name = "Aizen Dark", .data = @embedFile("themes/Aizen Dark") },
    .{ .name = "Aizen Light", .data = @embedFile("themes/Aizen Light") },
    .{ .name = "Alabaster", .data = @embedFile("themes/Alabaster") },
    .{ .name = "Alien Blood", .data = @embedFile("themes/Alien Blood") },
    .{ .name = "Andromeda", .data = @embedFile("themes/Andromeda") },
    .{ .name = "Apple Classic", .data = @embedFile("themes/Apple Classic") },
    .{ .name = "Apple System Colors", .data = @embedFile("themes/Apple System Colors") },
    .{ .name = "Apple System Colors Light", .data = @embedFile("themes/Apple System Colors Light") },
    .{ .name = "Arcoiris", .data = @embedFile("themes/Arcoiris") },
    .{ .name = "Ardoise", .data = @embedFile("themes/Ardoise") },
    .{ .name = "Argonaut", .data = @embedFile("themes/Argonaut") },
    .{ .name = "Arthur", .data = @embedFile("themes/Arthur") },
    .{ .name = "Atelier Sulphurpool", .data = @embedFile("themes/Atelier Sulphurpool") },
    .{ .name = "Atom", .data = @embedFile("themes/Atom") },
    .{ .name = "Atom One Dark", .data = @embedFile("themes/Atom One Dark") },
    .{ .name = "Atom One Light", .data = @embedFile("themes/Atom One Light") },
    .{ .name = "Aura", .data = @embedFile("themes/Aura") },
    .{ .name = "Aurora", .data = @embedFile("themes/Aurora") },
    .{ .name = "Ayu", .data = @embedFile("themes/Ayu") },
    .{ .name = "Ayu Light", .data = @embedFile("themes/Ayu Light") },
    .{ .name = "Ayu Mirage", .data = @embedFile("themes/Ayu Mirage") },
    .{ .name = "Banana Blueberry", .data = @embedFile("themes/Banana Blueberry") },
    .{ .name = "Batman", .data = @embedFile("themes/Batman") },
    .{ .name = "Belafonte Day", .data = @embedFile("themes/Belafonte Day") },
    .{ .name = "Belafonte Night", .data = @embedFile("themes/Belafonte Night") },
    .{ .name = "Birds Of Paradise", .data = @embedFile("themes/Birds Of Paradise") },
    .{ .name = "Black Metal", .data = @embedFile("themes/Black Metal") },
    .{ .name = "Black Metal (Bathory)", .data = @embedFile("themes/Black Metal (Bathory)") },
    .{ .name = "Black Metal (Burzum)", .data = @embedFile("themes/Black Metal (Burzum)") },
    .{ .name = "Black Metal (Dark Funeral)", .data = @embedFile("themes/Black Metal (Dark Funeral)") },
    .{ .name = "Black Metal (Gorgoroth)", .data = @embedFile("themes/Black Metal (Gorgoroth)") },
    .{ .name = "Black Metal (Immortal)", .data = @embedFile("themes/Black Metal (Immortal)") },
    .{ .name = "Black Metal (Khold)", .data = @embedFile("themes/Black Metal (Khold)") },
    .{ .name = "Black Metal (Marduk)", .data = @embedFile("themes/Black Metal (Marduk)") },
    .{ .name = "Black Metal (Mayhem)", .data = @embedFile("themes/Black Metal (Mayhem)") },
    .{ .name = "Black Metal (Nile)", .data = @embedFile("themes/Black Metal (Nile)") },
    .{ .name = "Black Metal (Venom)", .data = @embedFile("themes/Black Metal (Venom)") },
    .{ .name = "Blazer", .data = @embedFile("themes/Blazer") },
    .{ .name = "Blue Berry Pie", .data = @embedFile("themes/Blue Berry Pie") },
    .{ .name = "Blue Dolphin", .data = @embedFile("themes/Blue Dolphin") },
    .{ .name = "Blue Matrix", .data = @embedFile("themes/Blue Matrix") },
    .{ .name = "Bluloco Dark", .data = @embedFile("themes/Bluloco Dark") },
    .{ .name = "Bluloco Light", .data = @embedFile("themes/Bluloco Light") },
    .{ .name = "Borland", .data = @embedFile("themes/Borland") },
    .{ .name = "Box", .data = @embedFile("themes/Box") },
    .{ .name = "Breadog", .data = @embedFile("themes/Breadog") },
    .{ .name = "Breeze", .data = @embedFile("themes/Breeze") },
    .{ .name = "Bright Lights", .data = @embedFile("themes/Bright Lights") },
    .{ .name = "Broadcast", .data = @embedFile("themes/Broadcast") },
    .{ .name = "Brogrammer", .data = @embedFile("themes/Brogrammer") },
    .{ .name = "Builtin Dark", .data = @embedFile("themes/Builtin Dark") },
    .{ .name = "Builtin Light", .data = @embedFile("themes/Builtin Light") },
    .{ .name = "Builtin Pastel Dark", .data = @embedFile("themes/Builtin Pastel Dark") },
    .{ .name = "Builtin Tango Dark", .data = @embedFile("themes/Builtin Tango Dark") },
    .{ .name = "Builtin Tango Light", .data = @embedFile("themes/Builtin Tango Light") },
    .{ .name = "C64", .data = @embedFile("themes/C64") },
    .{ .name = "CGA", .data = @embedFile("themes/CGA") },
    .{ .name = "CLRS", .data = @embedFile("themes/CLRS") },
    .{ .name = "Calamity", .data = @embedFile("themes/Calamity") },
    .{ .name = "Carbonfox", .data = @embedFile("themes/Carbonfox") },
    .{ .name = "Catppuccin Frappe", .data = @embedFile("themes/Catppuccin Frappe") },
    .{ .name = "Catppuccin Latte", .data = @embedFile("themes/Catppuccin Latte") },
    .{ .name = "Catppuccin Macchiato", .data = @embedFile("themes/Catppuccin Macchiato") },
    .{ .name = "Catppuccin Mocha", .data = @embedFile("themes/Catppuccin Mocha") },
    .{ .name = "Chalk", .data = @embedFile("themes/Chalk") },
    .{ .name = "Chalkboard", .data = @embedFile("themes/Chalkboard") },
    .{ .name = "Challenger Deep", .data = @embedFile("themes/Challenger Deep") },
    .{ .name = "Chester", .data = @embedFile("themes/Chester") },
    .{ .name = "Ciapre", .data = @embedFile("themes/Ciapre") },
    .{ .name = "Citruszest", .data = @embedFile("themes/Citruszest") },
    .{ .name = "Cobalt Neon", .data = @embedFile("themes/Cobalt Neon") },
    .{ .name = "Cobalt Next", .data = @embedFile("themes/Cobalt Next") },
    .{ .name = "Cobalt Next Dark", .data = @embedFile("themes/Cobalt Next Dark") },
    .{ .name = "Cobalt Next Minimal", .data = @embedFile("themes/Cobalt Next Minimal") },
    .{ .name = "Cobalt2", .data = @embedFile("themes/Cobalt2") },
    .{ .name = "Coffee Theme", .data = @embedFile("themes/Coffee Theme") },
    .{ .name = "Crayon Pony Fish", .data = @embedFile("themes/Crayon Pony Fish") },
    .{ .name = "Cursor Dark", .data = @embedFile("themes/Cursor Dark") },
    .{ .name = "Cutie Pro", .data = @embedFile("themes/Cutie Pro") },
    .{ .name = "Cyberdyne", .data = @embedFile("themes/Cyberdyne") },
    .{ .name = "Cyberpunk", .data = @embedFile("themes/Cyberpunk") },
    .{ .name = "Cyberpunk Scarlet Protocol", .data = @embedFile("themes/Cyberpunk Scarlet Protocol") },
    .{ .name = "Dark Modern", .data = @embedFile("themes/Dark Modern") },
    .{ .name = "Dark Pastel", .data = @embedFile("themes/Dark Pastel") },
    .{ .name = "Dark+", .data = @embedFile("themes/Dark+") },
    .{ .name = "Darkermatrix", .data = @embedFile("themes/Darkermatrix") },
    .{ .name = "Darkmatrix", .data = @embedFile("themes/Darkmatrix") },
    .{ .name = "Darkside", .data = @embedFile("themes/Darkside") },
    .{ .name = "Dawnfox", .data = @embedFile("themes/Dawnfox") },
    .{ .name = "Dayfox", .data = @embedFile("themes/Dayfox") },
    .{ .name = "Deep", .data = @embedFile("themes/Deep") },
    .{ .name = "Desert", .data = @embedFile("themes/Desert") },
    .{ .name = "Detuned", .data = @embedFile("themes/Detuned") },
    .{ .name = "Dimidium", .data = @embedFile("themes/Dimidium") },
    .{ .name = "Dimmed Monokai", .data = @embedFile("themes/Dimmed Monokai") },
    .{ .name = "Django", .data = @embedFile("themes/Django") },
    .{ .name = "Django Reborn Again", .data = @embedFile("themes/Django Reborn Again") },
    .{ .name = "Django Smooth", .data = @embedFile("themes/Django Smooth") },
    .{ .name = "Doom One", .data = @embedFile("themes/Doom One") },
    .{ .name = "Doom Peacock", .data = @embedFile("themes/Doom Peacock") },
    .{ .name = "Dot Gov", .data = @embedFile("themes/Dot Gov") },
    .{ .name = "Dracula", .data = @embedFile("themes/Dracula") },
    .{ .name = "Dracula+", .data = @embedFile("themes/Dracula+") },
    .{ .name = "Duckbones", .data = @embedFile("themes/Duckbones") },
    .{ .name = "Duotone Dark", .data = @embedFile("themes/Duotone Dark") },
    .{ .name = "Duskfox", .data = @embedFile("themes/Duskfox") },
    .{ .name = "ENCOM", .data = @embedFile("themes/ENCOM") },
    .{ .name = "Earthsong", .data = @embedFile("themes/Earthsong") },
    .{ .name = "Electron Highlighter", .data = @embedFile("themes/Electron Highlighter") },
    .{ .name = "Elegant", .data = @embedFile("themes/Elegant") },
    .{ .name = "Elemental", .data = @embedFile("themes/Elemental") },
    .{ .name = "Elementary", .data = @embedFile("themes/Elementary") },
    .{ .name = "Embark", .data = @embedFile("themes/Embark") },
    .{ .name = "Embers Dark", .data = @embedFile("themes/Embers Dark") },
    .{ .name = "Espresso", .data = @embedFile("themes/Espresso") },
    .{ .name = "Espresso Libre", .data = @embedFile("themes/Espresso Libre") },
    .{ .name = "Everblush", .data = @embedFile("themes/Everblush") },
    .{ .name = "Everforest Dark Hard", .data = @embedFile("themes/Everforest Dark Hard") },
    .{ .name = "Everforest Light Med", .data = @embedFile("themes/Everforest Light Med") },
    .{ .name = "Fahrenheit", .data = @embedFile("themes/Fahrenheit") },
    .{ .name = "Fairyfloss", .data = @embedFile("themes/Fairyfloss") },
    .{ .name = "Farmhouse Dark", .data = @embedFile("themes/Farmhouse Dark") },
    .{ .name = "Farmhouse Light", .data = @embedFile("themes/Farmhouse Light") },
    .{ .name = "Fideloper", .data = @embedFile("themes/Fideloper") },
    .{ .name = "Firefly Traditional", .data = @embedFile("themes/Firefly Traditional") },
    .{ .name = "Firefox Dev", .data = @embedFile("themes/Firefox Dev") },
    .{ .name = "Firewatch", .data = @embedFile("themes/Firewatch") },
    .{ .name = "Fish Tank", .data = @embedFile("themes/Fish Tank") },
    .{ .name = "Flat", .data = @embedFile("themes/Flat") },
    .{ .name = "Flatland", .data = @embedFile("themes/Flatland") },
    .{ .name = "Flexoki Dark", .data = @embedFile("themes/Flexoki Dark") },
    .{ .name = "Flexoki Light", .data = @embedFile("themes/Flexoki Light") },
    .{ .name = "Floraverse", .data = @embedFile("themes/Floraverse") },
    .{ .name = "Forest Blue", .data = @embedFile("themes/Forest Blue") },
    .{ .name = "Framer", .data = @embedFile("themes/Framer") },
    .{ .name = "Front End Delight", .data = @embedFile("themes/Front End Delight") },
    .{ .name = "Fun Forrest", .data = @embedFile("themes/Fun Forrest") },
    .{ .name = "Galaxy", .data = @embedFile("themes/Galaxy") },
    .{ .name = "Galizur", .data = @embedFile("themes/Galizur") },
    .{ .name = "Ghostty Default Style Dark", .data = @embedFile("themes/Ghostty Default Style Dark") },
    .{ .name = "GitHub", .data = @embedFile("themes/GitHub") },
    .{ .name = "GitHub Dark", .data = @embedFile("themes/GitHub Dark") },
    .{ .name = "GitHub Dark Colorblind", .data = @embedFile("themes/GitHub Dark Colorblind") },
    .{ .name = "GitHub Dark Default", .data = @embedFile("themes/GitHub Dark Default") },
    .{ .name = "GitHub Dark Dimmed", .data = @embedFile("themes/GitHub Dark Dimmed") },
    .{ .name = "GitHub Dark High Contrast", .data = @embedFile("themes/GitHub Dark High Contrast") },
    .{ .name = "GitHub Light Colorblind", .data = @embedFile("themes/GitHub Light Colorblind") },
    .{ .name = "GitHub Light Default", .data = @embedFile("themes/GitHub Light Default") },
    .{ .name = "GitHub Light High Contrast", .data = @embedFile("themes/GitHub Light High Contrast") },
    .{ .name = "GitLab Dark", .data = @embedFile("themes/GitLab Dark") },
    .{ .name = "GitLab Dark Grey", .data = @embedFile("themes/GitLab Dark Grey") },
    .{ .name = "GitLab Light", .data = @embedFile("themes/GitLab Light") },
    .{ .name = "Glacier", .data = @embedFile("themes/Glacier") },
    .{ .name = "Grape", .data = @embedFile("themes/Grape") },
    .{ .name = "Grass", .data = @embedFile("themes/Grass") },
    .{ .name = "Grey Green", .data = @embedFile("themes/Grey Green") },
    .{ .name = "Gruber Darker", .data = @embedFile("themes/Gruber Darker") },
    .{ .name = "Gruvbox Dark", .data = @embedFile("themes/Gruvbox Dark") },
    .{ .name = "Gruvbox Dark Hard", .data = @embedFile("themes/Gruvbox Dark Hard") },
    .{ .name = "Gruvbox Light", .data = @embedFile("themes/Gruvbox Light") },
    .{ .name = "Gruvbox Light Hard", .data = @embedFile("themes/Gruvbox Light Hard") },
    .{ .name = "Gruvbox Material", .data = @embedFile("themes/Gruvbox Material") },
    .{ .name = "Gruvbox Material Dark", .data = @embedFile("themes/Gruvbox Material Dark") },
    .{ .name = "Gruvbox Material Light", .data = @embedFile("themes/Gruvbox Material Light") },
    .{ .name = "Guezwhoz", .data = @embedFile("themes/Guezwhoz") },
    .{ .name = "HaX0R Blue", .data = @embedFile("themes/HaX0R Blue") },
    .{ .name = "HaX0R Gr33N", .data = @embedFile("themes/HaX0R Gr33N") },
    .{ .name = "HaX0R R3D", .data = @embedFile("themes/HaX0R R3D") },
    .{ .name = "Hacktober", .data = @embedFile("themes/Hacktober") },
    .{ .name = "Hardcore", .data = @embedFile("themes/Hardcore") },
    .{ .name = "Harper", .data = @embedFile("themes/Harper") },
    .{ .name = "Havn Daggry", .data = @embedFile("themes/Havn Daggry") },
    .{ .name = "Havn Skumring", .data = @embedFile("themes/Havn Skumring") },
    .{ .name = "Heeler", .data = @embedFile("themes/Heeler") },
    .{ .name = "Highway", .data = @embedFile("themes/Highway") },
    .{ .name = "Hipster Green", .data = @embedFile("themes/Hipster Green") },
    .{ .name = "Hivacruz", .data = @embedFile("themes/Hivacruz") },
    .{ .name = "Homebrew", .data = @embedFile("themes/Homebrew") },
    .{ .name = "Hopscotch", .data = @embedFile("themes/Hopscotch") },
    .{ .name = "Hopscotch.256", .data = @embedFile("themes/Hopscotch.256") },
    .{ .name = "Horizon", .data = @embedFile("themes/Horizon") },
    .{ .name = "Horizon Bright", .data = @embedFile("themes/Horizon Bright") },
    .{ .name = "Hot Dog Stand", .data = @embedFile("themes/Hot Dog Stand") },
    .{ .name = "Hot Dog Stand (Mustard)", .data = @embedFile("themes/Hot Dog Stand (Mustard)") },
    .{ .name = "Hurtado", .data = @embedFile("themes/Hurtado") },
    .{ .name = "Hybrid", .data = @embedFile("themes/Hybrid") },
    .{ .name = "IBM 5153 CGA", .data = @embedFile("themes/IBM 5153 CGA") },
    .{ .name = "IBM 5153 CGA (Black)", .data = @embedFile("themes/IBM 5153 CGA (Black)") },
    .{ .name = "IC Green PPL", .data = @embedFile("themes/IC Green PPL") },
    .{ .name = "IC Orange PPL", .data = @embedFile("themes/IC Orange PPL") },
    .{ .name = "IR Black", .data = @embedFile("themes/IR Black") },
    .{ .name = "IRIX Console", .data = @embedFile("themes/IRIX Console") },
    .{ .name = "IRIX Terminal", .data = @embedFile("themes/IRIX Terminal") },
    .{ .name = "Iceberg Dark", .data = @embedFile("themes/Iceberg Dark") },
    .{ .name = "Iceberg Light", .data = @embedFile("themes/Iceberg Light") },
    .{ .name = "Idea", .data = @embedFile("themes/Idea") },
    .{ .name = "Idle Toes", .data = @embedFile("themes/Idle Toes") },
    .{ .name = "Jackie Brown", .data = @embedFile("themes/Jackie Brown") },
    .{ .name = "Japanesque", .data = @embedFile("themes/Japanesque") },
    .{ .name = "Jellybeans", .data = @embedFile("themes/Jellybeans") },
    .{ .name = "JetBrains Darcula", .data = @embedFile("themes/JetBrains Darcula") },
    .{ .name = "Jubi", .data = @embedFile("themes/Jubi") },
    .{ .name = "Kanagawa Dragon", .data = @embedFile("themes/Kanagawa Dragon") },
    .{ .name = "Kanagawa Wave", .data = @embedFile("themes/Kanagawa Wave") },
    .{ .name = "Kanagawabones", .data = @embedFile("themes/Kanagawabones") },
    .{ .name = "Kibble", .data = @embedFile("themes/Kibble") },
    .{ .name = "Kitty Default", .data = @embedFile("themes/Kitty Default") },
    .{ .name = "Kitty Low Contrast", .data = @embedFile("themes/Kitty Low Contrast") },
    .{ .name = "Kolorit", .data = @embedFile("themes/Kolorit") },
    .{ .name = "Konsolas", .data = @embedFile("themes/Konsolas") },
    .{ .name = "Kurokula", .data = @embedFile("themes/Kurokula") },
    .{ .name = "Lab Fox", .data = @embedFile("themes/Lab Fox") },
    .{ .name = "Laser", .data = @embedFile("themes/Laser") },
    .{ .name = "Later This Evening", .data = @embedFile("themes/Later This Evening") },
    .{ .name = "Lavandula", .data = @embedFile("themes/Lavandula") },
    .{ .name = "Light Owl", .data = @embedFile("themes/Light Owl") },
    .{ .name = "Liquid Carbon", .data = @embedFile("themes/Liquid Carbon") },
    .{ .name = "Liquid Carbon Transparent", .data = @embedFile("themes/Liquid Carbon Transparent") },
    .{ .name = "Lovelace", .data = @embedFile("themes/Lovelace") },
    .{ .name = "Man Page", .data = @embedFile("themes/Man Page") },
    .{ .name = "Mariana", .data = @embedFile("themes/Mariana") },
    .{ .name = "Material", .data = @embedFile("themes/Material") },
    .{ .name = "Material Dark", .data = @embedFile("themes/Material Dark") },
    .{ .name = "Material Darker", .data = @embedFile("themes/Material Darker") },
    .{ .name = "Material Design Colors", .data = @embedFile("themes/Material Design Colors") },
    .{ .name = "Material Ocean", .data = @embedFile("themes/Material Ocean") },
    .{ .name = "Mathias", .data = @embedFile("themes/Mathias") },
    .{ .name = "Matrix", .data = @embedFile("themes/Matrix") },
    .{ .name = "Matte Black", .data = @embedFile("themes/Matte Black") },
    .{ .name = "Medallion", .data = @embedFile("themes/Medallion") },
    .{ .name = "Melange Dark", .data = @embedFile("themes/Melange Dark") },
    .{ .name = "Melange Light", .data = @embedFile("themes/Melange Light") },
    .{ .name = "Mellifluous", .data = @embedFile("themes/Mellifluous") },
    .{ .name = "Mellow", .data = @embedFile("themes/Mellow") },
    .{ .name = "Miasma", .data = @embedFile("themes/Miasma") },
    .{ .name = "Midnight In Mojave", .data = @embedFile("themes/Midnight In Mojave") },
    .{ .name = "Mirage", .data = @embedFile("themes/Mirage") },
    .{ .name = "Misterioso", .data = @embedFile("themes/Misterioso") },
    .{ .name = "Molokai", .data = @embedFile("themes/Molokai") },
    .{ .name = "Mona Lisa", .data = @embedFile("themes/Mona Lisa") },
    .{ .name = "Monokai Classic", .data = @embedFile("themes/Monokai Classic") },
    .{ .name = "Monokai Pro", .data = @embedFile("themes/Monokai Pro") },
    .{ .name = "Monokai Pro Light", .data = @embedFile("themes/Monokai Pro Light") },
    .{ .name = "Monokai Pro Light Sun", .data = @embedFile("themes/Monokai Pro Light Sun") },
    .{ .name = "Monokai Pro Machine", .data = @embedFile("themes/Monokai Pro Machine") },
    .{ .name = "Monokai Pro Octagon", .data = @embedFile("themes/Monokai Pro Octagon") },
    .{ .name = "Monokai Pro Ristretto", .data = @embedFile("themes/Monokai Pro Ristretto") },
    .{ .name = "Monokai Pro Spectrum", .data = @embedFile("themes/Monokai Pro Spectrum") },
    .{ .name = "Monokai Remastered", .data = @embedFile("themes/Monokai Remastered") },
    .{ .name = "Monokai Soda", .data = @embedFile("themes/Monokai Soda") },
    .{ .name = "Monokai Vivid", .data = @embedFile("themes/Monokai Vivid") },
    .{ .name = "Moonfly", .data = @embedFile("themes/Moonfly") },
    .{ .name = "N0Tch2K", .data = @embedFile("themes/N0Tch2K") },
    .{ .name = "Neobones Dark", .data = @embedFile("themes/Neobones Dark") },
    .{ .name = "Neobones Light", .data = @embedFile("themes/Neobones Light") },
    .{ .name = "Neon", .data = @embedFile("themes/Neon") },
    .{ .name = "Neopolitan", .data = @embedFile("themes/Neopolitan") },
    .{ .name = "Neutron", .data = @embedFile("themes/Neutron") },
    .{ .name = "Night Lion V1", .data = @embedFile("themes/Night Lion V1") },
    .{ .name = "Night Lion V2", .data = @embedFile("themes/Night Lion V2") },
    .{ .name = "Night Owl", .data = @embedFile("themes/Night Owl") },
    .{ .name = "Night Owlish Light", .data = @embedFile("themes/Night Owlish Light") },
    .{ .name = "Nightfox", .data = @embedFile("themes/Nightfox") },
    .{ .name = "Niji", .data = @embedFile("themes/Niji") },
    .{ .name = "No Clown Fiesta", .data = @embedFile("themes/No Clown Fiesta") },
    .{ .name = "No Clown Fiesta Light", .data = @embedFile("themes/No Clown Fiesta Light") },
    .{ .name = "Nocturnal Winter", .data = @embedFile("themes/Nocturnal Winter") },
    .{ .name = "Nord", .data = @embedFile("themes/Nord") },
    .{ .name = "Nord Light", .data = @embedFile("themes/Nord Light") },
    .{ .name = "Nord Wave", .data = @embedFile("themes/Nord Wave") },
    .{ .name = "Nordfox", .data = @embedFile("themes/Nordfox") },
    .{ .name = "Novel", .data = @embedFile("themes/Novel") },
    .{ .name = "Nvim Dark", .data = @embedFile("themes/Nvim Dark") },
    .{ .name = "Nvim Light", .data = @embedFile("themes/Nvim Light") },
    .{ .name = "Obsidian", .data = @embedFile("themes/Obsidian") },
    .{ .name = "Ocean", .data = @embedFile("themes/Ocean") },
    .{ .name = "Oceanic Material", .data = @embedFile("themes/Oceanic Material") },
    .{ .name = "Oceanic Next", .data = @embedFile("themes/Oceanic Next") },
    .{ .name = "Ollie", .data = @embedFile("themes/Ollie") },
    .{ .name = "One Dark Two", .data = @embedFile("themes/One Dark Two") },
    .{ .name = "One Dark Pro", .data = @embedFile("themes/One Dark Pro") },
    .{ .name = "One Double Dark", .data = @embedFile("themes/One Double Dark") },
    .{ .name = "One Double Light", .data = @embedFile("themes/One Double Light") },
    .{ .name = "One Half Dark", .data = @embedFile("themes/One Half Dark") },
    .{ .name = "One Half Light", .data = @embedFile("themes/One Half Light") },
    .{ .name = "Onenord", .data = @embedFile("themes/Onenord") },
    .{ .name = "Onenord Light", .data = @embedFile("themes/Onenord Light") },
    .{ .name = "Operator Mono Dark", .data = @embedFile("themes/Operator Mono Dark") },
    .{ .name = "Overnight Slumber", .data = @embedFile("themes/Overnight Slumber") },
    .{ .name = "Oxocarbon", .data = @embedFile("themes/Oxocarbon") },
    .{ .name = "Pale Night Hc", .data = @embedFile("themes/Pale Night Hc") },
    .{ .name = "Pandora", .data = @embedFile("themes/Pandora") },
    .{ .name = "Paraiso Dark", .data = @embedFile("themes/Paraiso Dark") },
    .{ .name = "Paul Millr", .data = @embedFile("themes/Paul Millr") },
    .{ .name = "Pencil Dark", .data = @embedFile("themes/Pencil Dark") },
    .{ .name = "Pencil Light", .data = @embedFile("themes/Pencil Light") },
    .{ .name = "Peppermint", .data = @embedFile("themes/Peppermint") },
    .{ .name = "Phala Green Dark", .data = @embedFile("themes/Phala Green Dark") },
    .{ .name = "Piatto Light", .data = @embedFile("themes/Piatto Light") },
    .{ .name = "Pnevma", .data = @embedFile("themes/Pnevma") },
    .{ .name = "Poimandres", .data = @embedFile("themes/Poimandres") },
    .{ .name = "Poimandres Darker", .data = @embedFile("themes/Poimandres Darker") },
    .{ .name = "Poimandres Storm", .data = @embedFile("themes/Poimandres Storm") },
    .{ .name = "Poimandres White", .data = @embedFile("themes/Poimandres White") },
    .{ .name = "Popping And Locking", .data = @embedFile("themes/Popping And Locking") },
    .{ .name = "Powershell", .data = @embedFile("themes/Powershell") },
    .{ .name = "Primary", .data = @embedFile("themes/Primary") },
    .{ .name = "Pro", .data = @embedFile("themes/Pro") },
    .{ .name = "Pro Light", .data = @embedFile("themes/Pro Light") },
    .{ .name = "Purple Rain", .data = @embedFile("themes/Purple Rain") },
    .{ .name = "Purplepeter", .data = @embedFile("themes/Purplepeter") },
    .{ .name = "Rapture", .data = @embedFile("themes/Rapture") },
    .{ .name = "Raycast Dark", .data = @embedFile("themes/Raycast Dark") },
    .{ .name = "Raycast Light", .data = @embedFile("themes/Raycast Light") },
    .{ .name = "Rebecca", .data = @embedFile("themes/Rebecca") },
    .{ .name = "Red Alert", .data = @embedFile("themes/Red Alert") },
    .{ .name = "Red Planet", .data = @embedFile("themes/Red Planet") },
    .{ .name = "Red Sands", .data = @embedFile("themes/Red Sands") },
    .{ .name = "Relaxed", .data = @embedFile("themes/Relaxed") },
    .{ .name = "Retro", .data = @embedFile("themes/Retro") },
    .{ .name = "Retro Legends", .data = @embedFile("themes/Retro Legends") },
    .{ .name = "Rippedcasts", .data = @embedFile("themes/Rippedcasts") },
    .{ .name = "Rose Pine", .data = @embedFile("themes/Rose Pine") },
    .{ .name = "Rose Pine Dawn", .data = @embedFile("themes/Rose Pine Dawn") },
    .{ .name = "Rose Pine Moon", .data = @embedFile("themes/Rose Pine Moon") },
    .{ .name = "Rouge 2", .data = @embedFile("themes/Rouge 2") },
    .{ .name = "Royal", .data = @embedFile("themes/Royal") },
    .{ .name = "Ryuuko", .data = @embedFile("themes/Ryuuko") },
    .{ .name = "Sakura", .data = @embedFile("themes/Sakura") },
    .{ .name = "Scarlet Protocol", .data = @embedFile("themes/Scarlet Protocol") },
    .{ .name = "Sea Shells", .data = @embedFile("themes/Sea Shells") },
    .{ .name = "Seafoam Pastel", .data = @embedFile("themes/Seafoam Pastel") },
    .{ .name = "Selenized Black", .data = @embedFile("themes/Selenized Black") },
    .{ .name = "Selenized Dark", .data = @embedFile("themes/Selenized Dark") },
    .{ .name = "Selenized Light", .data = @embedFile("themes/Selenized Light") },
    .{ .name = "Seoulbones Dark", .data = @embedFile("themes/Seoulbones Dark") },
    .{ .name = "Seoulbones Light", .data = @embedFile("themes/Seoulbones Light") },
    .{ .name = "Seti", .data = @embedFile("themes/Seti") },
    .{ .name = "Shades Of Purple", .data = @embedFile("themes/Shades Of Purple") },
    .{ .name = "Shaman", .data = @embedFile("themes/Shaman") },
    .{ .name = "Slate", .data = @embedFile("themes/Slate") },
    .{ .name = "Sleepy Hollow", .data = @embedFile("themes/Sleepy Hollow") },
    .{ .name = "Smyck", .data = @embedFile("themes/Smyck") },
    .{ .name = "Snazzy", .data = @embedFile("themes/Snazzy") },
    .{ .name = "Snazzy Soft", .data = @embedFile("themes/Snazzy Soft") },
    .{ .name = "Soft Server", .data = @embedFile("themes/Soft Server") },
    .{ .name = "Solarized Darcula", .data = @embedFile("themes/Solarized Darcula") },
    .{ .name = "Solarized Dark Higher Contrast", .data = @embedFile("themes/Solarized Dark Higher Contrast") },
    .{ .name = "Solarized Dark Patched", .data = @embedFile("themes/Solarized Dark Patched") },
    .{ .name = "Solarized Osaka Night", .data = @embedFile("themes/Solarized Osaka Night") },
    .{ .name = "Sonokai", .data = @embedFile("themes/Sonokai") },
    .{ .name = "Spacedust", .data = @embedFile("themes/Spacedust") },
    .{ .name = "Spacegray", .data = @embedFile("themes/Spacegray") },
    .{ .name = "Spacegray Bright", .data = @embedFile("themes/Spacegray Bright") },
    .{ .name = "Spacegray Eighties", .data = @embedFile("themes/Spacegray Eighties") },
    .{ .name = "Spacegray Eighties Dull", .data = @embedFile("themes/Spacegray Eighties Dull") },
    .{ .name = "Spiderman", .data = @embedFile("themes/Spiderman") },
    .{ .name = "Spring", .data = @embedFile("themes/Spring") },
    .{ .name = "Square", .data = @embedFile("themes/Square") },
    .{ .name = "Squirrelsong Dark", .data = @embedFile("themes/Squirrelsong Dark") },
    .{ .name = "Srcery", .data = @embedFile("themes/Srcery") },
    .{ .name = "Starlight", .data = @embedFile("themes/Starlight") },
    .{ .name = "Sublette", .data = @embedFile("themes/Sublette") },
    .{ .name = "Subliminal", .data = @embedFile("themes/Subliminal") },
    .{ .name = "Sugarplum", .data = @embedFile("themes/Sugarplum") },
    .{ .name = "Sundried", .data = @embedFile("themes/Sundried") },
    .{ .name = "Symfonic", .data = @embedFile("themes/Symfonic") },
    .{ .name = "Synthwave", .data = @embedFile("themes/Synthwave") },
    .{ .name = "Synthwave Alpha", .data = @embedFile("themes/Synthwave Alpha") },
    .{ .name = "Synthwave Everything", .data = @embedFile("themes/Synthwave Everything") },
    .{ .name = "Tango Adapted", .data = @embedFile("themes/Tango Adapted") },
    .{ .name = "Tango Half Adapted", .data = @embedFile("themes/Tango Half Adapted") },
    .{ .name = "Tearout", .data = @embedFile("themes/Tearout") },
    .{ .name = "Teerb", .data = @embedFile("themes/Teerb") },
    .{ .name = "Terafox", .data = @embedFile("themes/Terafox") },
    .{ .name = "Terminal Basic", .data = @embedFile("themes/Terminal Basic") },
    .{ .name = "Terminal Basic Dark", .data = @embedFile("themes/Terminal Basic Dark") },
    .{ .name = "Thayer Bright", .data = @embedFile("themes/Thayer Bright") },
    .{ .name = "The Hulk", .data = @embedFile("themes/The Hulk") },
    .{ .name = "Tinacious Design Dark", .data = @embedFile("themes/Tinacious Design Dark") },
    .{ .name = "Tinacious Design Light", .data = @embedFile("themes/Tinacious Design Light") },
    .{ .name = "TokyoNight", .data = @embedFile("themes/TokyoNight") },
    .{ .name = "TokyoNight Day", .data = @embedFile("themes/TokyoNight Day") },
    .{ .name = "TokyoNight Moon", .data = @embedFile("themes/TokyoNight Moon") },
    .{ .name = "TokyoNight Night", .data = @embedFile("themes/TokyoNight Night") },
    .{ .name = "TokyoNight Storm", .data = @embedFile("themes/TokyoNight Storm") },
    .{ .name = "Tomorrow", .data = @embedFile("themes/Tomorrow") },
    .{ .name = "Tomorrow Night", .data = @embedFile("themes/Tomorrow Night") },
    .{ .name = "Tomorrow Night Blue", .data = @embedFile("themes/Tomorrow Night Blue") },
    .{ .name = "Tomorrow Night Bright", .data = @embedFile("themes/Tomorrow Night Bright") },
    .{ .name = "Tomorrow Night Burns", .data = @embedFile("themes/Tomorrow Night Burns") },
    .{ .name = "Tomorrow Night Eighties", .data = @embedFile("themes/Tomorrow Night Eighties") },
    .{ .name = "Toy Chest", .data = @embedFile("themes/Toy Chest") },
    .{ .name = "Treehouse", .data = @embedFile("themes/Treehouse") },
    .{ .name = "Twilight", .data = @embedFile("themes/Twilight") },
    .{ .name = "Ubuntu", .data = @embedFile("themes/Ubuntu") },
    .{ .name = "Ultra Dark", .data = @embedFile("themes/Ultra Dark") },
    .{ .name = "Ultra Violent", .data = @embedFile("themes/Ultra Violent") },
    .{ .name = "Under The Sea", .data = @embedFile("themes/Under The Sea") },
    .{ .name = "Unikitty", .data = @embedFile("themes/Unikitty") },
    .{ .name = "Urple", .data = @embedFile("themes/Urple") },
    .{ .name = "Vague", .data = @embedFile("themes/Vague") },
    .{ .name = "Vaughn", .data = @embedFile("themes/Vaughn") },
    .{ .name = "Vercel", .data = @embedFile("themes/Vercel") },
    .{ .name = "Vesper", .data = @embedFile("themes/Vesper") },
    .{ .name = "Vibrant Ink", .data = @embedFile("themes/Vibrant Ink") },
    .{ .name = "Vimbones", .data = @embedFile("themes/Vimbones") },
    .{ .name = "Violet Dark", .data = @embedFile("themes/Violet Dark") },
    .{ .name = "Violet Light", .data = @embedFile("themes/Violet Light") },
    .{ .name = "Violite", .data = @embedFile("themes/Violite") },
    .{ .name = "Warm Neon", .data = @embedFile("themes/Warm Neon") },
    .{ .name = "Wez", .data = @embedFile("themes/Wez") },
    .{ .name = "Whimsy", .data = @embedFile("themes/Whimsy") },
    .{ .name = "Wild Cherry", .data = @embedFile("themes/Wild Cherry") },
    .{ .name = "Wilmersdorf", .data = @embedFile("themes/Wilmersdorf") },
    .{ .name = "Wombat", .data = @embedFile("themes/Wombat") },
    .{ .name = "Wryan", .data = @embedFile("themes/Wryan") },
    .{ .name = "Xcode Dark", .data = @embedFile("themes/Xcode Dark") },
    .{ .name = "Xcode Dark hc", .data = @embedFile("themes/Xcode Dark hc") },
    .{ .name = "Xcode Light", .data = @embedFile("themes/Xcode Light") },
    .{ .name = "Xcode Light hc", .data = @embedFile("themes/Xcode Light hc") },
    .{ .name = "Xcode WWDC", .data = @embedFile("themes/Xcode WWDC") },
    .{ .name = "Zenbones", .data = @embedFile("themes/Zenbones") },
    .{ .name = "Zenbones Dark", .data = @embedFile("themes/Zenbones Dark") },
    .{ .name = "Zenbones Light", .data = @embedFile("themes/Zenbones Light") },
    .{ .name = "Zenburn", .data = @embedFile("themes/Zenburn") },
    .{ .name = "Zenburned", .data = @embedFile("themes/Zenburned") },
    .{ .name = "Zenwritten Dark", .data = @embedFile("themes/Zenwritten Dark") },
    .{ .name = "Zenwritten Light", .data = @embedFile("themes/Zenwritten Light") },
    .{ .name = "branch", .data = @embedFile("themes/branch") },
    .{ .name = "iTerm2 Dark Background", .data = @embedFile("themes/iTerm2 Dark Background") },
    .{ .name = "iTerm2 Default", .data = @embedFile("themes/iTerm2 Default") },
    .{ .name = "iTerm2 Light Background", .data = @embedFile("themes/iTerm2 Light Background") },
    .{ .name = "iTerm2 Pastel Dark Background", .data = @embedFile("themes/iTerm2 Pastel Dark Background") },
    .{ .name = "iTerm2 Smoooooth", .data = @embedFile("themes/iTerm2 Smoooooth") },
    .{ .name = "iTerm2 Solarized Dark", .data = @embedFile("themes/iTerm2 Solarized Dark") },
    .{ .name = "iTerm2 Solarized Light", .data = @embedFile("themes/iTerm2 Solarized Light") },
    .{ .name = "iTerm2 Tango Dark", .data = @embedFile("themes/iTerm2 Tango Dark") },
    .{ .name = "iTerm2 Tango Light", .data = @embedFile("themes/iTerm2 Tango Light") },
    .{ .name = "novmbr", .data = @embedFile("themes/novmbr") },
    .{ .name = "owl", .data = @embedFile("themes/owl") },
    .{ .name = "traffic", .data = @embedFile("themes/traffic") },
    .{ .name = "urban", .data = @embedFile("themes/urban") },
};

/// Look up an embedded theme by name (case-sensitive, like Ghostty).
pub fn get(name: []const u8) ?[]const u8 {
    for (&entries) |*entry| {
        if (std.mem.eql(u8, entry.name, name)) return entry.data;
    }
    return null;
}

test "One Dark Pro is an embedded theme" {
    const theme = get("One Dark Pro") orelse return error.ThemeNotFound;
    try std.testing.expect(std.mem.indexOf(u8, theme, "background = #282c34") != null);
    try std.testing.expect(std.mem.indexOf(u8, theme, "palette = 4=#4aa5f0") != null);
}
