"""Platform-agnostic driver contract. Test cases depend only on this. The
terminal-text layer (get_text/wait_for/primary_pane) is reused verbatim by a
future Windows backend; only the input + menu/window methods are reimplemented.
"""
from dataclasses import dataclass
from typing import Optional, Protocol, runtime_checkable


@dataclass
class ItemState:
    enabled: bool
    checked: Optional[bool] = None


@runtime_checkable
class Driver(Protocol):
    def launch(self, *, cols: int = 80, rows: int = 24) -> None: ...
    def quit(self) -> None: ...
    def focus(self) -> None: ...
    def primary_pane(self) -> str: ...
    # real input
    def key(self, key: str, *mods: str) -> None: ...
    def text(self, s: str) -> None: ...
    def click(self, x: int, y: int, *, count: int = 1) -> None: ...
    # menu / window
    def menu_click(self, *path: str) -> None: ...
    def menu_item_state(self, *path: str) -> ItemState: ...
    def window_attr(self, name: str) -> str: ...
    # terminal text (cross-platform)
    def get_text(self, pane: str, recent: Optional[int] = None) -> str: ...
    def wait_for(self, pane: str, pattern: str, timeout: float = 5.0) -> None: ...
